#!/bin/bash
clear
R='\e[1;91m'
G='\e[1;92m'
Y='\e[1;93m'
C='\e[1;96m'
N='\e[0m'
colornow=$(cat /etc/alawivpn/theme/color.conf)
export U="$(cat /etc/alawivpn/theme/$colornow | grep -w "TEXT" | cut -d: -f2|sed 's/ //g')"
export O="$(cat /etc/alawivpn/theme/$colornow | grep -w "BG" | cut -d: -f2|sed 's/ //g')"

# FUNCTIONKU
garis(){ echo -e " $U$*$N"; }
judul(){ echo -e " $O$*$N"; }
tebal(){ echo -e " $W$*$N"; }

# tema hehe
clear
echo
garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
tebal "  MENGHENTIKAN PROGRAMS DI LATAR BELAKANG  "
garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo
muslim=("urut" "unlockotomatis" "pindahmenu" "menu2" "menu3" "alawivpn" "cooling" "m-backup" "m-theme" "reset" "xp" "autocpu.bak" "delall" "m-bot" "m-trojan" "restore" "xraylimit" "bantwidth" "deltrialssh" "m-ip" "m-vless" "reuuid" "bottelegram" "deltrialv2ray" "m-sshovpn" "m-vmess" "running" "certv2ray" "dilarang" "m-system" "sixtydays" "cleaner" "jancok" "m-tcp" "onoff" "tendang" "menu")

paksa() {
    for alawi in "${muslim[@]}"; do
        pkill -f "/usr/local/sbin/$alawi"
        echo -e " Proses ${G}$alawi${N} ${R}dihentikan!${N}"
    done
    echo
    echo -e " ${C}Scrip By:${Y} Config-Santri™${N}"
    exit 0
}
paksa
