#!/bin/bash
G='\e[1;32m'
N='\e[0m'
# File .bashrc path
BASHRC_FILE="$HOME/.bashrc"

# Function to check and uncomment lines
uncomment_line() {
    local line="$1"
    if grep -q "^# $line" "$BASHRC_FILE"; then
        sed -i "s/^# \($line\)/\1/" "$BASHRC_FILE"
    fi
}

# Function to check and add aliases if they do not exist
add_alias() {
    local alias_cmd="$1"
    if ! grep -q "$alias_cmd" "$BASHRC_FILE"; then
        echo "$alias_cmd" >> "$BASHRC_FILE"
    fi
}

# Uncomment lines
uncomment_line "export LS_OPTIONS="
uncomment_line "alias ls="

# Add aliases
add_alias "alias +x='chmod +x'"
add_alias "alias status='systemctl status'"
add_alias "alias stop='systemctl stop'"
add_alias "alias restart='systemctl restart'"
add_alias "alias sh='bash'"
add_alias "alias c='clear'"
add_alias "alias x='exit'"
add_alias "alias py='python'"
add_alias "alias nn='nano'"
add_alias "alias cls='clear && ls'"
add_alias "alias cdx='cd .. && cls'"
add_alias "alias py3='python3'"
add_alias "alias py2='python2'"

cat <<'EOF'> /usr/bin/cpy
#!/bin/bash
G='\e[1;32m'
N='\e[0m'
f=$1
sudo cp $f /usr/bin/$f
chmod +x /usr/bin/$f
echo -e "Silahkan ketik ${G}${f}${N} untuk mencobanya"
exit 0
EOF

echo -e "ketik ${G}. ~/.bashrc${N} untuk menerapkan perubahan"
