#!/bin/bash
log_file="/root/checking.log"

log() {
    jumlah=$(cat $log_file | wc -l)
    nomor=$(printf "%02d)" $(($jumlah + 1)))
    echo "$nomor   $(date +"%Y-%m-%d   %H:%M:%S") $1" >> "$log_file"
}

jumlah=$(cat $log_file | wc -l)
if [[ $jumlah -gt 300 ]]; then
    > $log_file
fi

clear
masuk=$(who | grep -w "root" | wc -l)
if [[ $masuk -eq 0 ]]; then
    a
    log "  Script pembersihan berhasil"
    exit 0
else
    exit 0
fi
