#!/bin/bash
exit_clean() { echo " Dihentikan"; exit 0; }
trap exit_clean SIGINT
IP=$(curl -sS ipv4.icanhazip.com)
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
domain=$(cat /etc/xray/domain)
author=$(cat /etc/profil)
TIMES="10"
CHATID=$(cat /etc/botexp/id)
KEY=$(cat /etc/botexp/token)
URL="https://api.telegram.org/bot$KEY/sendMessage"

# Path ke file akun trial list
data_vmess="/etc/xray/trialvmess"
data_vless="/etc/xray/trialvless"
data_trojan="/etc/xray/trialtrojan"

# Mendapatkan tanggal dan waktu saat ini
now=$(date +"%Y-%m-%d %H:%M:%S")

# Fungsi untuk memproses data
process_data() {
    local data_file=$1
    local protocol=$2

    while IFS= read -r line; do
        if [[ $line == *"Trial"* ]]; then
            user=$(echo "$line" | awk '{print $2}')
            exp1=$(echo "$line" | awk '{print $3, $4}')
            exp=$(echo "$line" | awk '{print $3}')
            diff=$(( $(date -d "$exp1" +%s) - $(date -d "$now" +%s) ))

            if [[ $diff -le 0 ]]; then
                echo "Menghapus izin untuk pengguna: $user"

                # Pastikan perintah sed pertama berhasil
                while ! sed -i "/^#${protocol} $user $exp/,/^},{/d" /etc/xray/config.json; do
                    sleep 1
                done

                # Pastikan perintah sed kedua berhasil
                while ! sed -i "/^#${protocol}g $user $exp/,/^},{/d" /etc/xray/config.json; do
                    sleep 1
                done

                # Pastikan perintah sed ketiga berhasil
                while ! sed -i "/${line}/d" "$data_file"; do
                    sleep 1
                done

                case $protocol in
                    vm)
                        rm /etc/vmess/${user}IP >/dev/null 2>&1
                        rm /home/vps/public_html/vmess-${user}.txt >/dev/null 2>&1
                        rm /etc/vmess/${user}login >/dev/null 2>&1
                        ;;
                    vl)
                        rm /etc/vless/${user}IP >/dev/null 2>&1
                        rm /home/vps/public_html/vless-${user}.txt >/dev/null 2>&1
                        rm /etc/vless/${user}login >/dev/null 2>&1
                        ;;
                    tr)
                        rm /etc/trojan/${user}IP >/dev/null 2>&1
                        rm /home/vps/public_html/trojan-${user}.txt >/dev/null 2>&1
                        rm /etc/trojan/${user}login >/dev/null 2>&1
                        ;;
                esac

                systemctl restart xray >/dev/null 2>&1

                case $protocol in
                    vm) jenis="VMESS" ;;
                    vl) jenis="VLESS" ;;
                    tr) jenis="TROJAN" ;;
                esac

                TEXT="
━━━━━━━━━━━━━━━━━━━━━━━
      <b>☘️ EXPIRED TRIAL ${jenis} ☘️</b>
━━━━━━━━━━━━━━━━━━━━━━━
<b>» User :</b> <code>$user</code>
<b>» Domain :</b> <code>$domain</code>
<b>» SUDAH EXPIRED</b>
━━━━━━━━━━━━━━━━━━━━━━━
» @alawivpn
━━━━━━━━━━━━━━━━━━━━━━━
"
                curl -s --max-time "$TIMES" -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" "$URL" >/dev/null
            fi
        fi
    done < "$data_file"
}

# Memproses data VMESS
process_data "$data_vmess" "vm"

# Memproses data VLESS
process_data "$data_vless" "vl"

# Memproses data TROJAN
process_data "$data_trojan" "tr"

exit 0
