#!/bin/bash
clear
exit_clean() { echo " Dihentikan"; exit 0; }
trap exit_clean SIGINT
clear
colornow=$(cat /etc/alawivpn/theme/color.conf)
export U="$(cat /etc/alawivpn/theme/$colornow | grep -w "TEXT" | cut -d: -f2|sed 's/ //g')"
export O="$(cat /etc/alawivpn/theme/$colornow | grep -w "BG" | cut -d: -f2|sed 's/ //g')"
export R='\033[1;31m'
export G='\033[1;32m'
export N='\e[0m'
lebar=44
myip=$(curl -sS ipv4.icanhazip.com)
penyamaan() { lebar_judul=${#judul}; peluasan=$(( (lebar - lebar_judul) /2 -1 )); padding=""; for ((i=0; i<peluasan; i++)); do padding+=" "; done; }
cetak_judul() { printf "${U}%s${N}${O}%s${tebal}%s%s${N}${U}%s%s\n" "│" "$padding" "$judul" "$padding" "│"; }
cetak() { lebarjudul=${#judul}; if (( lebarjudul % 2 == 1 )); then printf "${U}%s${warna}%s%s%s${N}${U}%s%s\n" "│" "$padding" "$judul" "$padding" " " "│"; else printf "${U}%s${warna}%s%s%s${N}${U}%s%s\n" "│" "$padding" "$judul" "$padding" "│"; fi; }
judul1() { warna="${R}"; judul="PERIZINAN DILARANG"; penyamaan; }
judul2() { warna="${N}"; judul="IP KAMU : $myip"; penyamaan; }
judul3() { warna="${R}"; judul="Tidak mendapatkan izin"; penyamaan; }
judul4() { warna="${N}"; judul="Silahkan hubungi Admin"; penyamaan; }
judul5() { warna="${N}"; judul="Telegram : @alawivpn"; penyamaan; }
okok() { echo -e "$U$*$N"; }
clear
echo
okok "╭══════════════════════════════════════════╮"
judul1; cetak_judul
okok "╰══════════════════════════════════════════╯"
okok "╭══════════════════════════════════════════╮"
judul2; cetak
judul3; cetak
judul4; cetak
judul5; cetak
okok "╰══════════════════════════════════════════╯"
exit 0
