#!/bin/bash
exit_clean() { echo " Dihentikan"; exit 0; }
trap exit_clean SIGINT
REPOKU="https://raw.githubusercontent.com/optimus-glitch/newsc/main"
REPOSC="https://raw.githubusercontent.com/optimus-glitch/newsc/main"
biji=`date +"%Y-%m-%d" -d "$dateFromServer"`
colornow=$(cat /etc/alawivpn/theme/color.conf)
NC="\e[0m"
R='\e[1;91m'
COLOR1="$(cat /etc/alawivpn/theme/$colornow | grep -w "TEXT" | cut -d: -f2|sed 's/ //g')"
COLBG1="$(cat /etc/alawivpn/theme/$colornow | grep -w "BG" | cut -d: -f2|sed 's/ //g')"
WH='\033[1;37m'
U=$COLOR1
O=$COLBG1
W=$WH
N=$NC
ipsaya=$(wget -qO- ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="${REPOKU}/registrasi.txt"
checking_sc() {
    useexp=$(curl -sS "$data_ip" | grep "$ipsaya" | awk '{print $3}')
    [[ "$date_list" > "$useexp" ]] && { systemctl stop nginx kyt xray ws-stunnel; dilarang; exit 1; }
}
checking_sc
author=$(cat /etc/profil)
lebar=54
judul="$author"
penyamaan() {
    lebar_judul=${#judul}
    peluasan=$(( (lebar - lebar_judul) /2 -1 ))
    padding=""
    for ((i=0; i<peluasan; i++)); do
        padding+=" "
    done
}
cetak_judul(){
    penyamaan
    if (( lebar_judul % 2 == 1 )); then
        printf " $U%s$N%s$W%s$N%s$U%s$N\n" "│" "$padding" "$judul" "$padding " "│"
    else
        printf " $U%s$N%s$W%s$N%s$U%s$N\n" "│" "$padding" "$judul" "$padding" "│"
    fi
}

# FUNGSIKU
garis() { echo -e " $U$*$N"; }
judul() { echo -e " $O$*$N"; }
tebal() { echo -e " $W$*$N"; }
kembali() { read -n 1 -s -r -p "  Press any key to back on menu "; }

ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
author=$(cat /etc/profil)
TIMES="10"
CHATID=$(cat /etc/per/id)
KEY=$(cat /etc/per/token)
URL="https://api.telegram.org/bot$KEY/sendMessage"
domain=`cat /etc/xray/domain`
CHATID2=$(cat /etc/perlogin/id)
KEY2=$(cat /etc/perlogin/token)
URL2="https://api.telegram.org/bot$KEY2/sendMessage"
cd
if [ ! -e /etc/trojan/akun ]; then
    mkdir -p /etc/trojan/akun
fi
function add-tr(){
    clear
    until [[ $user =~ ^[a-zA-Z0-9_.-]+$ && ${USER_EXISTS} == '0' ]]; do
        echo -e " ${U}╭═════════════════════════════════════════════════╮${N}"
        echo -e " ${U}│${O}            ● Add Trojan Account ●               ${N}${U}│ ${N}"
        echo -e " ${U}╰═════════════════════════════════════════════════╯${N}"
        echo -e ""
        read -rp "  User: " -e user
        USER_EXISTS=$(grep -w $user /etc/xray/config.json | wc -l)
        if [[ ${USER_EXISTS} == '1' ]]; then
            clear
            echo -e " ${U}╭═════════════════════════════════════════════════╮${N}"
            echo -e " ${U}│${O}            ● Add Trojan Account ●         ${N}${U}│ ${N}"
            echo -e " ${U}╰═════════════════════════════════════════════════╯${N}"
            echo -e " ${U}╭═════════════════════════════════════════════════╮${N}"
            echo -e " ${U}│                                                 │"
            echo -e " ${U}│${W} Nama Duplikat Silahkan Buat Nama Lain.          ${U}│"
            echo -e " ${U}│                                                 │"
            echo -e " ${U}╰═════════════════════════════════════════════════╯${N}"
            kembali
            add-tr
        fi
    done
    uuid=$(cat /proc/sys/kernel/random/uuid)
    until [[ $masaaktif =~ ^[0-9]+$ ]]; do
        read -p "  Expired (hari): " masaaktif
    done
    exp=`date -d "$masaaktif days" +"%Y-%m-%d"`
    until [[ $iplim =~ ^[0-9]+$ ]]; do
        read -p "  Limit User (IP) or 0 Unlimited: " iplim
    done
    until [[ $Quota =~ ^[0-9]+$ ]]; do
        read -p "  Limit User (GB) or 0 Unlimited: " Quota
    done
    if [ ! -e /etc/trojan ]; then
        mkdir -p /etc/trojan
    fi
    if [ ${iplim} = '0' ]; then
        iplim="999999999"
    fi
    if [ ${Quota} = '0' ]; then
        Quota="999999999"
    fi
    c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
    d=$((${c} * 1024 * 1024 * 1024))
    if [[ ${c} != "0" ]]; then
        echo "${d}" >/etc/trojan/${user}
    fi
    echo "${iplim}" >/etc/trojan/${user}IP
sed -i '/#trojanws$/a\#tr '"$user $exp $uuid"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#trojangrpc$/a\#trg '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
    trojanlink1="trojan://${uuid}@${domain}:443?mode=gun&security=tls&type=grpc&serviceName=trojan-grpc&sni=${domain}#${user}"
    trojanlink="trojan://${uuid}@${domain}:443?path=%2Ftrojan-ws&security=tls&host=${domain}&type=ws&sni=${domain}#${user}"
    trojan1="trojan://${uuid}@${domain}:443?mode=gun%26security=tls%26type=grpc%26serviceName=trojan-grpc%26sni=${domain}#${user}"
    trojan2="trojan://${uuid}@${domain}:443?path=%2Ftrojan-ws%26security=tls%26host=${domain}%26type=ws%26sni=${domain}#${user}"
cat > /home/vps/public_html/trojan-$user.txt <<-END
-------------------------------------------
Format Trojan WS (CDN)
-------------------------------------------
- name: Trojan-$user-WS (CDN)
server: ${domain}
port: 443
type: trojan
password: ${uuid}
network: ws
sni: ${domain}
skip-cert-verify: true
udp: true
ws-opts:
path: /trojan-ws
headers:
Host: ${domain}
-------------------------------------------
Format Trojan gRPC
-------------------------------------------
- name: Trojan-$user-gRPC (SNI)
type: trojan
server: ${domain}
port: 443
password: ${uuid}
udp: true
sni: ${domain}
skip-cert-verify: true
network: grpc
grpc-opts:
grpc-service-name: trojan-grpc
-------------------------------------------
Link Trojan Account
-------------------------------------------
Link WS : trojan://${uuid}@${domain}:443?path=%2Ftrojan-ws&security=tls&host=${domain}&type=ws&sni=${domain}#${user}
-------------------------------------------
Link GRPC : trojan://${uuid}@${domain}:443?mode=gun&security=tls&type=grpc&serviceName=trojan-grpc&sni=${domain}#${user}
-------------------------------------------
END
    if [ ${Quota} = '9999' ]; then
        TEXT="
════════════════════
Premium Trojan Account
════════════════════
User         : ${user}
Domain       : <code>${domain}</code>
Login Limit  : ${iplim} IP
Quota Limit  : ${Quota} GB
ISP          : ${ISP}
CITY         : ${CITY}
Port TLS     : 443
Port gRPC    : 443
UUID         : <code>${uuid}</code>
AlterId      : 0
Security     : auto
Network      : WS or gRPC
Path TLS     : <code>/trojan-ws</code>
Path gRPC    : <code>/trojan-grpc</code>
════════════════════
Link TLS    :
<code>${trojan2}</code>
════════════════════
Link GRPC    :
<code>${trojan1}</code>
════════════════════
Format OpenClash :
http://$domain:89/trojan-$user.txt
════════════════════
Expired Until    :  $exp
════════════════════
$author
════════════════════
"
    else
        TEXT="
━━━━━━━━━━━━━━━━━━━━━━━
<b>☘️ Premium Trojan Account ☘️</b>
━━━━━━━━━━━━━━━━━━━━━━━
<code>User        :</code> <code>${user}</code>
<code>Domain      :</code> <code>${domain}</code>
<code>Login Limit :</code> <code>${iplim} IP</code>
<code>Quota Limit :</code> <code>${Quota} GB</code>
<code>ISP         :</code> <code>${ISP}</code>
<code>CITY        :</code> <code>${CITY}</code>
<code>Port TLS    :</code> <code>443</code>
<code>Port gRPC   :</code> <code>443</code>
<code>UUID        :</code> <code>${uuid}</code>
<code>AlterId     :</code> <code>0</code>
<code>Security    :</code> <code>auto</code>
<code>Network     :</code> <code>WS or gRPC</code>
<code>Path TLS    :</code> <code>/trojan-ws</code>
<code>Path gRPC   :</code> <code>/trojan-grpc</code>
━━━━━━━━━━━━━━━━━━━━━━━
<b>Link TLS    :</b>
<code>${trojan2}</code>
━━━━━━━━━━━━━━━━━━━━━━━
<b>Link GRPC    :</b>
<code>${trojan1}</code>
━━━━━━━━━━━━━━━━━━━━━━━
<b>Format OpenClash :</b>
http://${domain}:89/trojan-${user}.txt
━━━━━━━━━━━━━━━━━━━━━━━
<code>Expired Until :</code> <b>${exp}</b>
━━━━━━━━━━━━━━━━━━━━━━━
<b>${author}</b>
━━━━━━━━━━━━━━━━━━━━━━━
"
    fi
    curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
    cd
    if [ ! -e /etc/tele ]; then
        echo -ne
    else
        echo "$TEXT" > /etc/notiftele
        bash /etc/tele
    fi
    user2=$(echo "$user" | cut -c 1-3)
    TIME2=$(date +'%Y-%m-%d %H:%M:%S')
    TEXT2="
━━━━━━━━━━━━━━━━━━━━━━━
<b>    ☘ TROJAN PREMIUM SOLD ☘</b>
━━━━━━━━━━━━━━━━━━━━━━━
<code>Order  :</code> <code>TROJAN Premium</code>
<code>User   :</code> <code>${user2}⬤⬤⬤</code>
<code>Domain :</code> <code>${domain}</code>
<code>ISP    :</code> <code>${ISP}</code>
<code>CITY   :</code> <code>$CITY</code>
<code>Date   :</code> <code>${TIME2} WIB</code>
<code>Limit  :</code> <code>${iplim} IP</code>
<code>Aktif  :</code> <code>$masaaktif Hari</code>
━━━━━━━━━━━━━━━━━━━━━━━
<i>Succes create this trojan account..</i>"
    curl -s --max-time $TIMES -d "chat_id=$CHATID2&disable_web_page_preview=1&text=$TEXT2&parse_mode=html" $URL2 >/dev/null
    clear
echo -e "━━━━━━━━━━━━━━━━━━━━━━━ " | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "● Premium Trojan Account ●  " | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "━━━━━━━━━━━━━━━━━━━━━━━ " | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "User         : ${user}" | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "ISP          : $ISP" | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "City         : $CITY" | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "Host         : ${domain}" | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "Login Limit  : ${iplim} IP" | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "Quota Limit  : ${Quota} GB" | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "Port TLS     : 443" | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "Port gRPC    : 443" | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "Key          : ${uuid}" | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "Path WS      : /trojan-ws" | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "Path gRPC    : /trojan-grpc" | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "━━━━━━━━━━━━━━━━━━━━━━━ " | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "Link TLS     : " | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "${trojanlink}" | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "━━━━━━━━━━━━━━━━━━━━━━━ " | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "Link gRPC    : " | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "${trojanlink1}" | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "━━━━━━━━━━━━━━━━━━━━━━━ " | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "Format Openclash : " | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "http://$domain:89/trojan-$user.txt" | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "━━━━━━━━━━━━━━━━━━━━━━━ " | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "Expired Until   : $exp" | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "━━━━━━━━━━━━━━━━━━━━━━━ " | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "    $author     " | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "━━━━━━━━━━━━━━━━━━━━━━━ " | tee -a /etc/trojan/akun/log-create-${user}.log
echo | tee -a /etc/trojan/akun/log-create-${user}.log
    systemctl restart xray > /dev/null 2>&1
    bottelegram > /dev/null 2>&1 &
    kembali
    exec menu && exit 0
}

function trial-trojan(){
    clear
    cd
    echo -e " ${U}╭═════════════════════════════════════════════════╮${N}"
    echo -e " ${U}│${O}            ● Trial Trojan Account ●             ${N}${U}│ ${N}"
    echo -e " ${U}╰═════════════════════════════════════════════════╯${N}"
    echo -e ""
    until [[ $timer =~ ^[0-9]+$ ]]; do
        read -p "  Expired (Minutes): " timer
    done
    user=Trial-`</dev/urandom tr -dc X-Z-0-9 | head -c4`
    uuid=$(cat /proc/sys/kernel/random/uuid)
    masaaktif=0
    iplim=1
    Quota=10
    if [ ! -e /etc/trojan ]; then
        mkdir -p /etc/trojan
    fi
    c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
    d=$((${c} * 1024 * 1024 * 1024))
    if [[ ${c} != "0" ]]; then
        echo "${d}" >/etc/trojan/${user}
    fi
    echo "${iplim}" > /etc/trojan/${user}IP
    ecp=$(date -d "+$timer minutes" +"%Y-%m-%d %H:%M:%S")
    exp=$(echo $ecp | awk '{print $1}')
    touch /etc/xray/trialtrojan
    echo -e "### $user $ecp" >> /etc/xray/trialtrojan
sed -i '/#trojanws$/a\#tr '"$user $exp $uuid"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#trojangrpc$/a\#trg '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
    trojanlink1="trojan://${uuid}@${domain}:443?mode=gun&security=tls&type=grpc&serviceName=trojan-grpc&sni=bug.com#${user}"
    trojanlink="trojan://${uuid}@${domain}:443?path=%2Ftrojan-ws&security=tls&host=${domain}&type=ws&sni=${domain}#${user}"
    trojan1="trojan://${uuid}@${domain}:443?mode=gun%26security=tls%26type=grpc%26serviceName=trojan-grpc%26sni=${domain}#${user}"
    trojan2="trojan://${uuid}@${domain}:443?path=%2Ftrojan-ws%26security=tls%26host=${domain}%26type=ws%26sni=${domain}#${user}"
    cat > /home/vps/public_html/trojan-$user.txt <<-END
-------------------------------------------
Format Trojan WS (CDN)
-------------------------------------------
- name: Trojan-$user-WS (CDN)
server: ${domain}
port: 443
type: trojan
password: ${uuid}
network: ws
sni: ${domain}
skip-cert-verify: true
udp: true
ws-opts:
path: /trojan-ws
headers:
Host: ${domain}
-------------------------------------------
Format Trojan gRPC
-------------------------------------------
- name: Trojan-$user-gRPC (SNI)
type: trojan
server: ${domain}
port: 443
password: ${uuid}
udp: true
sni: ${domain}
skip-cert-verify: true
network: grpc
grpc-opts:
grpc-service-name: trojan-grpc
-------------------------------------------
Link Trojan Account
-------------------------------------------
Link TLS : trojan://${uuid}@${domain}:443?path=%2Ftrojan-ws&security=tls&host=${domain}&type=ws&sni=${domain}#${user}
-------------------------------------------
Link gRPC : trojan://${uuid}@${domain}:443?mode=gun&security=tls&type=grpc&serviceName=trojan-grpc&sni=${domain}#${user}
-------------------------------------------
END
    TEXT="
━━━━━━━━━━━━━━━━━━━━━━━
<b>☘️ Trial Premium Trojan Account ☘️</b>
━━━━━━━━━━━━━━━━━━━━━━━
<code>User         :</code> <code>${user}</code>
<code>Domain       :</code> <code>${domain}</code>
<code>Login Limit  :</code> <code>${iplim} IP</code>
<code>ISP          :</code> <code>${ISP}</code>
<code>CITY         :</code> <code>${CITY}</code>
<code>Port TLS     :</code> <code>443</code>
<code>Port gRPC    :</code> <code>443</code>
<code>UUID         :</code> <code>${uuid}</code>
<code>AlterId      :</code> <code>0</code>
<code>Security     :</code> <code>auto</code>
<code>Network      :</code> <code>WS or gRPC</code>
<code>Path WS      :</code> <code>/trojan-ws</code>
<code>Path GRPC    :</code> <code>/trojan-grpc</code>
━━━━━━━━━━━━━━━━━━━━━━━
<b>Link TLS    :</b>
<code>${trojan2}</code>
━━━━━━━━━━━━━━━━━━━━━━━
<b>Link gRPC    :</b>
<code>${trojan1}</code>
━━━━━━━━━━━━━━━━━━━━━━━
<b>Format OpenClash :</b>
http://${domain}:89/trojan-${user}.txt
━━━━━━━━━━━━━━━━━━━━━━━
<code>Expired :</code> <b>${ecp}</b>
━━━━━━━━━━━━━━━━━━━━━━━
<b>${author}</b>
━━━━━━━━━━━━━━━━━━━━━━━
"
    curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
    cd
    if [ ! -e /etc/tele ]; then
        echo -ne
    else
        echo "$TEXT" > /etc/notiftele
        bash /etc/tele
    fi
    clear
echo -e "━━━━━━━━━━━━━━━━━━━━━━━ " | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "● Trial Premium Trojan Account ●  " | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "━━━━━━━━━━━━━━━━━━━━━━━ " | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "User         : ${user}" | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "ISP          : $ISP" | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "City         : $CITY" | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "Host         : ${domain}" | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "Login Limit  : ${iplim} IP" | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "Port TLS     : 443" | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "Port gRPC    : 443" | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "UUID         : ${uuid}" | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "Path TLS     : /trojan-ws" | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "Path gRPC    : /trojan-grpc" | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "━━━━━━━━━━━━━━━━━━━━━━━ " | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "Link TLS     : " | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "${trojanlink}" | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "━━━━━━━━━━━━━━━━━━━━━━━ " | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "Link gRPC    : " | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "${trojanlink1}" | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "━━━━━━━━━━━━━━━━━━━━━━━ " | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "Format Openclash : " | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "http://$domain:89/trojan-$user.txt" | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "━━━━━━━━━━━━━━━━━━━━━━━ " | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "Expired : $ecp" | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "━━━━━━━━━━━━━━━━━━━━━━━ " | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "    $author     " | tee -a /etc/trojan/akun/log-create-${user}.log
echo -e "━━━━━━━━━━━━━━━━━━━━━━━ " | tee -a /etc/trojan/akun/log-create-${user}.log
echo | tee -a /etc/trojan/akun/log-create-${user}.log
    systemctl restart xray > /dev/null 2>&1
    kembali
    exec menu && exit 0
}
function renew-tr(){
    clear
    NUMBER_OF_CLIENTS=$(grep -c -E "^#tr " "/etc/xray/config.json")
    if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
        clear
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        judul "      ◈ Renew Trojan Account ◈     "
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo
        tebal "          Tidak ada user!!"
        echo
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo
        kembali
        exec $0 && exit 0
    fi
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    judul "      ◈ Renew Trojan Account ◈     "
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    tebal "Please choose the client to renew"
    tebal "Ketik [0] kembali ke menu"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    printf "${W}  %-5s %-15s %s\n" "No" "Name" "Expired"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    grep -E "^#tr " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | nl -s ') ' | while read -r line; do
        number=$(echo "$line" | cut -d')' -f 1 | xargs); name=$(echo "$line" | cut -d' ' -f 2); expired=$(echo "$line" | cut -d' ' -f 3-)
        printf "  %-5s %-15s %s\n" "$number" "$name" "$expired"
    done
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
        if [[ ${CLIENT_NUMBER} == '1' ]]; then
            read -rp " Select one client [1]: " CLIENT_NUMBER
        else
            read -rp " Select one client [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER
            if [[ ${CLIENT_NUMBER} == '0' ]]; then
                exec $0 && exit 0
            fi
        fi
    done
    read -p " Days extend: " masaaktif
    user=$(grep -E "^#tr " "/etc/xray/config.json" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
    exp=$(grep -E "^#tr " "/etc/xray/config.json" | cut -d ' ' -f 3 | sed -n "${CLIENT_NUMBER}"p)
    now=$(date +%Y-%m-%d)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    exp2=$(( (d1 - d2) / 86400 ))
    exp3=$(($exp2 + $masaaktif))
    exp4=`date -d "$exp3 days" +"%Y-%m-%d"`
    sed -i "s/#tr $user $exp/#tr $user $exp4/g" /etc/xray/config.json
    sed -i "s/#trg $user $exp/#trg $user $exp4/g" /etc/xray/config.json
    clear
    TEXT="
━━━━━━━━━━━━━━━━━━━━━━━
<b>☘️ XRAY TROJAN RENEW ☘️</b>
━━━━━━━━━━━━━━━━━━━━━━━
<code>User    :</code> <code>$user</code>
<code>Domain  :</code> <code>${domain}</code>
<code>ISP     :</code> <code>$ISP</code>
<code>CITY    :</code> <code>$CITY</code>
<code>Expired :</code> <code>$exp4</code>
━━━━━━━━━━━━━━━━━━━━━━━
<i>Succes Renew This Account..</i>
"
    curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
    cd
    if [ ! -e /etc/tele ]; then
        echo -ne
    else
        echo "$TEXT" > /etc/notiftele
        bash /etc/tele
    fi
    user2=$(echo "$user" | cut -c 1-3)
    TIME2=$(date +'%Y-%m-%d %H:%M:%S')
    TEXT2="
━━━━━━━━━━━━━━━━━━━━━━━
<b>     ☘ TROJAN PREMIUM SOLD ☘</b>
━━━━━━━━━━━━━━━━━━━━━━━
<code>Order  :</code> <code>TROJAN Premium</code>
<code>User   :</code> <code>${user2}⬤⬤⬤</code>
<code>Domain :</code> <code>${domain}</code>
<code>ISP    :</code> <code>$ISP</code>
<code>CITY   :</code> <code>$CITY</code>
<code>Date   :</code> <code>${TIME2} WIB</code>
<code>Aktif  :</code> <code>$masaaktif Hari</code>
━━━━━━━━━━━━━━━━━━━━━━━
<i>Succes Renew This Account...</i>
"
    curl -s --max-time $TIMES -d "chat_id=$CHATID2&disable_web_page_preview=1&text=$TEXT2&parse_mode=html" $URL2 >/dev/null
    clear
    systemctl restart xray > /dev/null 2>&1
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    judul "Trojan Account Was Successfully Renewed"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo
    echo " Client Name : $user"
    echo " Expired On  : $exp4"
    echo
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo
    bottelegram > /dev/null 2>&1 &
    kembali
    exec $0 && exit 0
}
function limit-tr(){
    clear
    NUMBER_OF_CLIENTS=$(grep -c -E "^#tr " "/etc/xray/config.json")
    if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
        clear
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        judul "      ◈ Limit Trojan Account ◈     "
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo
        tebal "          Tidak ada user!!"
        echo
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo
        kembali
        exec $0 && exit 0
    fi
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    judul "      ◈ Limit Trojan Account ◈     "
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    tebal "Please choose the client to change ip"
    tebal "Ketik [0] kembali ke menu"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    printf "${W}  %-5s %-15s %s\n" "No" "Name" "Expired"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    grep -E "^#tr " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | nl -s ') ' | while read -r line; do
        number=$(echo "$line" | cut -d')' -f 1 | xargs); name=$(echo "$line" | cut -d' ' -f 2); expired=$(echo "$line" | cut -d' ' -f 3-)
        printf "  %-5s %-15s %s\n" "$number" "$name" "$expired"
    done
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
        if [[ ${CLIENT_NUMBER} == '1' ]]; then
            read -rp " Select one client [1]: " CLIENT_NUMBER
        else
            read -rp " Select one client [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER
            if [[ ${CLIENT_NUMBER} == '0' ]]; then
                exec $0 && exit 0
            fi
        fi
    done
    clear
    until [[ $iplim =~ ^[0-9]+$ ]]; do
        read -p " Limit User (IP) or 0 Unlimited: " iplim
    done
    until [[ $Quota =~ ^[0-9]+$ ]]; do
        read -p " Limit User (GB) or 0 Unlimited: " Quota
    done
    if [ ! -e /etc/trojan ]; then
        mkdir -p /etc/trojan
    fi
    if [ ${iplim} = '0' ]; then
        iplim="999999999"
    fi
    if [ ${Quota} = '0' ]; then
        Quota="999999999"
    fi
    user=$(grep -E "^#tr " "/etc/xray/config.json" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
    echo "${iplim}" >/etc/trojan/${user}IP
    c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
    d=$((${c} * 1024 * 1024 * 1024))
    if [[ ${c} != "0" ]]; then
        echo "${d}" >/etc/trojan/${user}
    fi
    TEXT="
━━━━━━━━━━━━━━━━━━━━━━━
<b>☘️ XRAY TROJAN IP LIMIT ☘️</b>
━━━━━━━━━━━━━━━━━━━━━━━
<code>User    :</code> <code>$user</code>
<code>Domain  :</code> <code>${domain}</code>
<code>ISP     :</code> <code>$ISP</code>
<code>CITY    :</code> <code>$CITY</code>
<code>New Limit IP :</code> <code>$iplim IP</code>
<code>New Limit Quota :</code> <code>$Quota GB</code>
━━━━━━━━━━━━━━━━━━━━━━━
<i>Succes Change Limit This Account...</i>
"
    curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
    cd
    if [ ! -e /etc/tele ]; then
        echo -ne
    else
        echo "$TEXT" > /etc/notiftele
        bash /etc/tele
    fi
    clear
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    judul "     Successfully Change Limit     "
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo
    echo " Client Name : $user"
    echo " Limit IP    : $iplim IP"
    echo " Limit Quota : $Quota GB"
    echo
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo
    bottelegram > /dev/null 2>&1 &
    kembali
    exec $0 && exit 0
}

function del-tr(){
    clear
    NUMBER_OF_CLIENTS=$(grep -c -E "^#tr " "/etc/xray/config.json")
    if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        judul "     ◈ Delete Trojan Account ◈     "
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo
        tebal "          Tidak ada user!!"
        echo
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        kembali
        exec $0 && exit 0
    fi
    clear
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    judul "     ◈ Delete Trojan Account ◈     "
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    tebal "Please choose the client to remove"
    tebal "Ketik [0] kembali ke menu"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    printf "${W}  %-5s %-15s %s\n" "No" "Name" "Expired"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    grep -E "^#tr " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | nl -s ') ' | while read -r line; do
        number=$(echo "$line" | cut -d')' -f 1 | xargs); name=$(echo "$line" | cut -d' ' -f 2); expired=$(echo "$line" | cut -d' ' -f 3-)
        printf "  %-5s %-15s %s\n" "$number" "$name" "$expired"
    done
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
        if [[ ${CLIENT_NUMBER} == '1' ]]; then
            read -rp " Select one client [1]: " CLIENT_NUMBER
        else
            read -rp " Select one client [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER
            if [[ ${CLIENT_NUMBER} == '0' ]]; then
                exec $0 && exit 0
            fi
        fi
    done
    user=$(grep -E "^#tr " "/etc/xray/config.json" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
    exp=$(grep -E "^#tr " "/etc/xray/config.json" | cut -d ' ' -f 3 | sed -n "${CLIENT_NUMBER}"p)
    uuid=$(grep -E "^#tr " "/etc/xray/config.json" | cut -d ' ' -f 4 | sed -n "${CLIENT_NUMBER}"p)
    if [ ! -e /etc/trojan/akundelete ]; then
        echo > /etc/trojan/akundelete
    fi
    clear
    echo "### $user $exp $uuid" >> /etc/trojan/akundelete
    sed -i "/^#tr $user $exp/,/^},{/d" /etc/xray/config.json
    sed -i "/^#trg $user $exp/,/^},{/d" /etc/xray/config.json
    rm  /etc/trojan/${user}IP >/dev/null 2>&1
    clear
    rm /home/vps/public_html/trojan-$user.txt >/dev/null 2>&1
    rm /etc/trojan/${user}login >/dev/null 2>&1
    systemctl restart xray > /dev/null 2>&1
    clear
    TEXT="
━━━━━━━━━━━━━━━━━━━━━━━
<b>☘️ XRAY TROJAN DELETE ☘️</b>
━━━━━━━━━━━━━━━━━━━━━━━
<code>User    :</code> <code>$user</code>
<code>Domain  :</code> <code>${domain}</code>
<code>ISP     :</code> <code>$ISP</code>
<code>CITY    :</code> <code>$CITY</code>
<code>Expired :</code> <code>$exp</code>
━━━━━━━━━━━━━━━━━━━━━━━
<i>Succes Delete This Account...</i>
"
    curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
    cd
    if [ ! -e /etc/tele ]; then
        echo -ne
    else
        echo "$TEXT" > /etc/notiftele
        bash /etc/tele
    fi
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    judul "Trojan Account Deleted Successfully"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo " Client Name : $user"
    echo " Expired On  : $exp"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo
    kembali
    exec $0 && exit 0
}

tim2sec() {
    mult=1
    arg="$1"
    inu=0
    while [ ${#arg} -gt 0 ]; do
        prev="${arg%:*}"
        if [ "$prev" = "$arg" ]; then
            curr="${arg#0}"
            prev=""
        else
            curr="${arg##*:}"
            curr="${curr#0}"
        fi
        curr="${curr%.*}"
        inu=$((inu + curr * mult))
        mult=$((mult * 60))
        arg="$prev"
    done
    echo "$inu"
}

function convert() {
    local -i bytes=$1
    if [[ $bytes -lt 1024 ]]; then
        echo "${bytes} B"
    elif [[ $bytes -lt 1048576 ]]; then
        echo "$(awk "BEGIN {printf \"%.2f\", $bytes/1024}" | sed 's/\.00$//' | sed 's/\.\([0-9]\)0$/.\1/') KB"
    elif [[ $bytes -lt 1073741824 ]]; then
        echo "$(awk "BEGIN {printf \"%.2f\", $bytes/1048576}" | sed 's/\.00$//' | sed 's/\.\([0-9]\)0$/.\1/') MB"
    else
        echo "$(awk "BEGIN {printf \"%.2f\", $bytes/1073741824}" | sed 's/\.00$//' | sed 's/\.\([0-9]\)0$/.\1/') GB"
    fi
}

function cek-tr(){
    clear
    xrayy=$(cat /var/log/xray/access.log | wc -l)
    if [[ xrayy -le 5 ]]; then
        systemctl restart xray
    fi
    xraylimit
    echo -e " ${U}╭═════════════════════════════════════════════════╮${N}"
    echo -e " ${U}│${N}${O}             ${W}● TROJAN USER ONLINE ●              ${N}${U}│ ${N}"
    echo -e " ${U}╰═════════════════════════════════════════════════╯${N}"
    echo -e " ${U}╭═════════════════════════════════════════════════╮${N}"
    tr=($(cat /etc/xray/config.json | grep "^#trg" | awk '{print $2}' | sort -u))
    echo -n >/tmp/tr
    for db1 in ${tr[@]}; do
        logtr=$(cat /var/log/xray/access.log | grep -w "email: ${db1}" | tail -n 100)
        while read a; do
            if [[ -n ${a} ]]; then
                set -- ${a}
                ina="${7}"
                inu="${2}"
                anu="${3}"
                enu=$(echo "${anu}" | sed 's/tcp://g' | sed '/^$/d' | cut -d. -f1,2,3)
                now=$(tim2sec ${timenow})
                client=$(tim2sec ${inu})
                nowt=$(((${now} - ${client})))
                if [[ ${nowt} -lt 40 ]]; then
                    cat /tmp/tr | grep -w "${ina}" | grep -w "${enu}" >/dev/null
                    if [[ $? -eq 1 ]]; then
                        echo "${ina} ${inu} WIB : ${enu}" >>/tmp/tr
                        spltr=$(cat /tmp/tr)
                    fi
                fi
            fi
        done <<<"${logtr}"
    done
    if [[ ${spltr} != "" ]]; then
        printf " ${U}%-5s${W}%-15s%-12s%-12s%-8s${U}%s\n" "│" "USERNAME" "LOGIN" "USAGE" "LIMIT" "│"
        echo -e " ${U}├═════════════════════════════════════════════════┤${N}"
        for truser in ${tr[@]}; do
            trhas=$(cat /tmp/tr | grep -w "${truser}" | wc -l)
            tess=0
            if [[ ${trhas} -gt $tess ]]; then
                byt=$(cat /etc/limit/trojan/${truser})
                gb=$(convert ${byt})
                lim=$(cat /etc/trojan/${truser})
                lim2=$(convert ${lim})
                printf " ${U}%-5s\e[0;33m%-17s%-10s%-12s%-8s${U}%s\n" "│" "$truser" "$trhas" "$gb" "$lim2" "│"
            fi
        done
    else
        echo -e " ${U}│                                                 │"
        echo -e " ${U}│${W}             TIDAK ADA USER ONLINE!              ${U}│${N}"
        echo -e " ${U}│                                                 │"
        echo -e " ${U}╰═════════════════════════════════════════════════╯${N}"
        read -n 1 -s -r -p "  Press any key to back on menu"
        exec menu && exit 0
    fi

    echo -e " ${U}╰═════════════════════════════════════════════════╯${N}"
    echo -e " ${U}╭═════════════════════════════════════════════════╮${N}"
    echo -e " ${U}│${W}          CODE BY : ALAWI CONFIG-SANTRI          ${U}│${N}"
    echo -e " ${U}╰═════════════════════════════════════════════════╯${N}"
    echo
    read -n 1 -s -r -p "  Press any key to back on menu"
    exec $0 && exit 0
}
function list-trojan(){
    clear
    NUMBER_OF_CLIENTS=$(grep -c -E "^#tr " "/etc/xray/config.json")
    if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        judul "     ◈ Config Trojan Account ◈     "
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo
        tebal "          Tidak ada user!!"
        echo
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        kembali
        exec $0 && exit 0
    fi
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    judul "     ◈ Config Trojan Account ◈     "
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    tebal "Please choose the client to view the config"
    tebal "Ketik [0] kembali ke menu"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    printf "${W}  %-5s %-15s %s\n" "No" "Name" "Expired"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    grep -E "^#tr " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | nl -s ') ' | while read -r line; do
        number=$(echo "$line" | cut -d')' -f 1 | xargs); name=$(echo "$line" | cut -d' ' -f 2); expired=$(echo "$line" | cut -d' ' -f 3-)
        printf "  %-5s %-15s %s\n" "$number" "$name" "$expired"
    done
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
        if [[ ${CLIENT_NUMBER} == '1' ]]; then
            read -rp " Select one client [1]: " CLIENT_NUMBER
        else
            read -rp " Select one client [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER
            if [[ ${CLIENT_NUMBER} == '0' ]]; then
                exec $0 && exit 0
            fi
        fi
    done
    user=$(grep -E "^#tr " "/etc/xray/config.json" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
    clear
    cat /etc/trojan/akun/log-create-${user}.log
    cat /etc/trojan/akun/log-create-${user}.log > /etc/notifakun
    sed -i 's/\x1B\[1;37m//g' /etc/notifakun
    sed -i 's/\x1B\[0;96m//g' /etc/notifakun
    sed -i 's/\x1B\[0m//g' /etc/notifakun
    TEXT=$(cat /etc/notifakun)
    curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
    cd
    if [ ! -e /etc/tele ]; then
        echo -ne
    else
    echo "$TEXT" > /etc/notiftele
        bash /etc/tele
    fi
    kembali
    exec $0 && exit 0
}

function login-tr(){
    clear
    echo -e " ${U}╭═══════════════════════════════════════════════╮${N}"
    echo -e " ${U}│${N}${O}           ${W}● SETTING MULTI LOGIN ●             ${N}${U}│ ${N}"
    echo -e " ${U}╰═══════════════════════════════════════════════╯${N}"
    echo -e " ${U}╭═══════════════════════════════════════════════╮${N}"
    echo -e " ${U}│ ${N} SILAHKAN TULIS JUMLAH NOTIFIKASI UNTUK LOCK    ${N}"
    echo -e " ${U}│ ${N} AKUN USER YANG MULTI LOGIN     ${N}"
    echo -e " ${U}╰═══════════════════════════════════════════════╯${N}"
    read -rp "   Jika Mau 3x Notif baru kelock tulis 3, dst: " -e notif
    cd /etc/trojan
    echo "$notif" > notif
    clear
    echo -e " ${U}╭═══════════════════════════════════════════════╮${N}"
    echo -e " ${U}│${N}${O}           ${W}● SETTING MULTI LOGIN ●             ${N}${U}│ ${N}"
    echo -e " ${U}╰═══════════════════════════════════════════════╯${N}"
    echo -e " ${U}╭═══════════════════════════════════════════════╮${N}"
    echo -e " ${U}│ ${N} SUKSES GANTI NOTIF LOCK JADI $notif ${N} "
    echo -e " ${U}╰═══════════════════════════════════════════════╯${N}"
    kembali
    exec $0 && exit 0
}

function lock-tr(){
    clear
    cd
    if [ ! -e  /etc/trojan/listlock ]; then
        echo > /etc/trojan/listlock
    fi
    NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/trojan/listlock")
    if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        judul "     ◈ Unlock Trojan Account ◈     "
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo
        tebal "          Tidak ada user!!"
        echo
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        kembali
        exec $0 && exit 0
    fi
    clear
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    judul "     ◈ Unlock Trojan Account ◈     "
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    tebal "Please choose the client to Unlock"
    tebal "Ketik [0] kembali ke menu"
    tebal "Ketik [999] untuk delete semua Akun"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    printf "${W}  %-5s %-15s %s\n" "No" "Name" "Expired"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

    grep -E "^### " "/etc/trojan/listlock" | cut -d ' ' -f 2-3 | nl -s ') ' | while read -r line; do
        number=$(echo "$line" | cut -d')' -f 1 | xargs); name=$(echo "$line" | cut -d' ' -f 2); expired=$(echo "$line" | cut -d' ' -f 3-)
        printf "  %-5s %-15s %s\n" "$number" "$name" "$expired"
    done

    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
        if [[ ${CLIENT_NUMBER} == '1' ]]; then
            read -rp " Select one client [1]: " CLIENT_NUMBER
        else
            read -rp " Select one client [1-${NUMBER_OF_CLIENTS}] to Unlock: " CLIENT_NUMBER
            if [[ ${CLIENT_NUMBER} == '0' ]]; then
                exec $0 && exit 0
            fi
            if [[ ${CLIENT_NUMBER} == '999' ]]; then
                rm /etc/trojan/listlock
                exec $0 && exit 0
            fi
        fi
    done
    user=$(grep -E "^### " "/etc/trojan/listlock" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
    exp=$(grep -E "^### " "/etc/trojan/listlock" | cut -d ' ' -f 3 | sed -n "${CLIENT_NUMBER}"p)
    uuid=$(grep -E "^### " "/etc/trojan/listlock" | cut -d ' ' -f 4 | sed -n "${CLIENT_NUMBER}"p)
sed -i '/#trojanws$/a\#tr '"$user $exp $uuid"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#trojangrpc$/a\#trg '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i "/^### $user $exp $uuid/d" /etc/trojan/listlock
    systemctl restart xray
    TEXT="
━━━━━━━━━━━━━━━━━━━━━━━
<b>☘️ XRAY TROJAN UNLOCK ☘️</b>
━━━━━━━━━━━━━━━━━━━━━━━
<code>User    :</code> <code>$user</code>
<code>Domain  :</code> <code>${domain}</code>
<code>ISP     :</code> <code>$ISP</code>
<code>CITY    :</code> <code>$CITY</code>
<code>Expired :</code> <code>$exp</code>
━━━━━━━━━━━━━━━━━━━━━━━
<i>Succes Unlock This Account...</i>
"
    curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
    cd
    if [ ! -e /etc/tele ]; then
        echo -ne
    else
        echo "$TEXT" > /etc/notiftele
        bash /etc/tele
    fi
    clear
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    judul " Trojan Account Unlock Successfully"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo " Client Name : $user"
    echo " Status      : Unlocked"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo
    bottelegram > /dev/null 2>&1 &
    kembali
    exec $0 && exit 0
}

function res-user(){
    clear
    cd
    if [ ! -e /etc/trojan/akundelete ]; then
        echo > /etc/trojan/akundelete
    fi
    clear
    NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/trojan/akundelete")
    if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        judul "     ◈ Restore Trojan Account ◈    "
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo
        tebal "          Tidak ada user!!"
        echo
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        kembali
        exec $0 && exit 0
    fi
    clear
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    judul "     ◈ Restore Trojan Account ◈    "
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    tebal "Please choose the client to Restore"
    tebal "Ketik [0] kembali ke menu"
    tebal "Ketik [999] untuk delete semua Akun"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    printf "${W}  %-5s %-15s %s\n" "No" "Name" "Expired"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

    grep -E "^### " "/etc/trojan/akundelete" | cut -d ' ' -f 2-3 | nl -s ') ' | while read -r line; do
        number=$(echo "$line" | cut -d')' -f 1 | xargs); name=$(echo "$line" | cut -d' ' -f 2); expired=$(echo "$line" | cut -d' ' -f 3-)
        printf "  %-5s %-15s %s\n" "$number" "$name" "$expired"
    done

    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
        if [[ ${NUMBER_OF_CLIENTS} == '1' ]]; then
            read -rp " Select one client [1]: " CLIENT_NUMBER
        else
            read -rp " Select one client [1-${NUMBER_OF_CLIENTS}] to Unlock: " CLIENT_NUMBER
            if [[ ${CLIENT_NUMBER} == '0' ]]; then
                exec $0 && exit 0
            fi
            if [[ ${CLIENT_NUMBER} == '999' ]]; then
                rm /etc/trojan/akundelete
                exec $0 && exit 0
            fi
        fi
    done
    until [[ $masaaktif =~ ^[0-9]+$ ]]; do
        read -p " Expired (days): " masaaktif
    done
    until [[ $iplim =~ ^[0-9]+$ ]]; do
        read -p " Limit User (IP) or 0 Unlimited: " iplim
    done
    until [[ $Quota =~ ^[0-9]+$ ]]; do
        read -p " Limit Quota (GB) or 0 Unlimited: " Quota
    done
    if [ ${iplim} = '0' ]; then
        iplim="999999999"
    fi
    if [ ${Quota} = '0' ]; then
        Quota="999999999"
    fi
    user=$(grep -E "^### " "/etc/trojan/akundelete" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
    exp=$(grep -E "^### " "/etc/trojan/akundelete" | cut -d ' ' -f 3 | sed -n "${CLIENT_NUMBER}"p)
    uuid=$(grep -E "^### " "/etc/trojan/akundelete" | cut -d ' ' -f 4 | sed -n "${CLIENT_NUMBER}"p)
    newdate=$(date -d "$masaaktif days" +"%Y-%m-%d")
sed -i '/#trojanws$/a\#tr '"$user $newdate $uuid"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#trojangrpc$/a\#trg '"$user $newdate"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
    echo "${iplim}" >/etc/trojan/${user}IP
    c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
    d=$((${c} * 1024 * 1024 * 1024))
    if [[ ${c} != "0" ]]; then
        echo "${d}" >/etc/trojan/${user}
    fi
    sed -i "/^### ${user} ${exp} ${uuid}/d" /etc/trojan/akundelete
    systemctl restart xray
TEXT="
━━━━━━━━━━━━━━━━━━━━━━━
<b>☘️ XRAY TROJAN RESTORE ☘️</b>
━━━━━━━━━━━━━━━━━━━━━━━
<code>User     :</code> <code>$user</code>
<code>Domain   :</code> <code>${domain}</code>
<code>ISP      :</code> <code>$ISP</code>
<code>CITY     :</code> <code>$CITY</code>
<code>IP Limit :</code> <code>$iplim IP</code>
<code>Quota Limit :</code> <code>$Quota GB</code>
<code>Expired  :</code> <code>$newdate</code>
━━━━━━━━━━━━━━━━━━━━━━━
<i>Succes Restore This Account...</i>
"
    curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
    cd
    if [ ! -e /etc/tele ]; then
        echo -ne
    else
        echo "$TEXT" > /etc/notiftele
        bash /etc/tele
    fi
    clear
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    judul "Trojan Account Restore Successfully"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo " DOMAIN   : $domain"
    echo " ISP      : $ISP $CITY"
    echo " USERNAME : $user"
    echo " IP LIMIT : $iplim IP"
    echo " EXPIRED  : $newdate"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo
    bottelegram > /dev/null 2>&1 &
    kembali
    exec $0 && exit 0
}

function quota-user(){
    clear
    cd
    if [ ! -e  /etc/trojan/userQuota ]; then
        echo > /etc/trojan/userQuota
    fi
    NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/trojan/userQuota")
    if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        judul "     ◈ Unlock Trojan Account ◈     "
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo
        tebal "          Tidak ada user!!"
        echo
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        kembali
        exec $0 && exit 0
    fi
    clear
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    judul "     ◈ Unlock Trojan Account ◈     "
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    tebal "Please choose the client to Unlock"
    tebal "Ketik [0] kembali ke menu"
    tebal "Ketik [999] untuk delete semua Akun"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    printf "${W}  %-5s %-15s %s\n" "No" "Name" "Expired"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

    grep -E "^### " "/etc/trojan/userQuota" | cut -d ' ' -f 2-3 | nl -s ') ' | while read -r line; do
        number=$(echo "$line" | cut -d')' -f 1 | xargs); name=$(echo "$line" | cut -d' ' -f 2); expired=$(echo "$line" | cut -d' ' -f 3-)
        printf "  %-5s %-15s %s\n" "$number" "$name" "$expired"
    done

    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
        if [[ ${CLIENT_NUMBER} == '1' ]]; then
            read -rp " Select one client [1]: " CLIENT_NUMBER
        else
            read -rp " Select one client [1-${NUMBER_OF_CLIENTS}] to Unlock: " CLIENT_NUMBER
            if [[ ${CLIENT_NUMBER} == '0' ]]; then
                exec $0 && exit 0
            fi
            if [[ ${CLIENT_NUMBER} == '999' ]]; then
                rm /etc/trojan/userQuota
                exec $0 && exit 0
            fi
        fi
    done
    user=$(grep -E "^### " "/etc/trojan/userQuota" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
    exp=$(grep -E "^### " "/etc/trojan/userQuota" | cut -d ' ' -f 3 | sed -n "${CLIENT_NUMBER}"p)
    uuid=$(grep -E "^### " "/etc/trojan/userQuota" | cut -d ' ' -f 4 | sed -n "${CLIENT_NUMBER}"p)
sed -i '/#trojanws$/a\#tr '"$user $exp $uuid"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#trojangrpc$/a\#trg '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i "/^### $user $exp $uuid/d" /etc/trojan/userQuota
    systemctl restart xray
    TEXT="
━━━━━━━━━━━━━━━━━━━━━━━
<b>☘️ XRAY TROJAN UNLOCK ☘️</b>
━━━━━━━━━━━━━━━━━━━━━━━
<code>User    :</code> <code>$user</code>
<code>Domain  :</code> <code>${domain}</code>
<code>ISP     :</code> <code>$ISP</code>
<code>CITY    :</code> <code>$CITY</code>
<code>Expired :</code> <code>$exp</code>
━━━━━━━━━━━━━━━━━━━━━━━
<i>Succes Unlock This Account...</i>
"
    curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
    cd
    if [ ! -e /etc/tele ]; then
        echo -ne
    else
        echo "$TEXT" > /etc/notiftele
        bash /etc/tele
    fi
    clear
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    judul " Trojan Account Unlock Successfully"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo " Client Name : $user"
    echo " Status      : Unlocked"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo
    bottelegram > /dev/null 2>&1 &
    kembali
    exec $0 && exit 0
}
clear
author=$(cat /etc/profil)
echo -e " ${U}╭════════════════════════════════════════════════════╮${N}"
echo -e " ${U}│${N}${O}                ${W}● TROJAN PANEL MENU ●               ${N}${U}│${N}"
echo -e " ${U}╰════════════════════════════════════════════════════╯${N}"
echo -e " ${U}╭════════════════════════════════════════════════════╮${N}"
echo -e " ${U}│${N} ${W}[${U}01${W}]${N} ${U}● ${W}ADD AKUN${N}          ${W}[${U}06${W}]${N} ${U}● ${W}CEK USER CONFIG${N}    ${U}│${N}"
echo -e " ${U}│${N} ${W}[${U}02${W}]${N} ${U}● ${W}TRIAL AKUN${N}        ${W}[${U}07${W}]${N} ${U}● ${W}CHANGE USER LIMIT${N}  ${U}│${N}"
echo -e " ${U}│${N} ${W}[${U}03${W}]${N} ${U}● ${W}RENEW AKUN${N}        ${W}[${U}08${W}]${N} ${U}● ${W}SETTING LOCK LOGIN${N} ${U}│${N}"
echo -e " ${U}│${N} ${W}[${U}04${W}]${N} ${U}● ${W}DELETE AKUN${N}       ${W}[${U}09${W}]${N} ${U}● ${W}UNLOCK USER LOGIN${N}  ${U}│${N}"
echo -e " ${U}│${N} ${W}[${U}05${W}]${N} ${U}● ${W}CEK USER LOGIN${N}    ${W}[${U}10${W}]${N} ${U}● ${W}UNLOCK USER QUOTA ${N} ${U}│${N}"
echo -e " ${U}│${N} ${W}[${U}00${W}]${N} ${U}● ${W}GO BACK${N}           ${W}[${U}11${W}]${N} ${U}● ${W}RESTORE AKUN   ${N}    ${U}│${N}"
echo -e " ${U}╰════════════════════════════════════════════════════╯${N}"
echo -e " ${U}╭══════════════════════${W} ● BY${N} ● ${U}══════════════════════╮${N}"
cetak_judul
echo -e " ${U}╰════════════════════════════════════════════════════╯${N}"
echo -ne "  ${W}Select menu ${U}: ${W}"; read opt
case $opt in
	01 | 1) clear ; add-tr ; exit 0 ;;
	02 | 2) clear ; trial-trojan ; exit 0 ;;
	03 | 3) clear ; renew-tr ; exit 0 ;;
	04 | 4) clear ; del-tr ; exit 0 ;;
	05 | 5) clear ; cek-tr ; exit 0 ;;
	06 | 6) clear ; list-trojan ; exit 0 ;;
	07 | 7) clear ; limit-tr ; exit 0 ;;
	08 | 8) clear ; login-tr ; exit 0 ;;
	09 | 9) clear ; lock-tr ; exit 0 ;;
	10 | 10) clear ; quota-user ; exit 0 ;;
	11 | 11) clear ; res-user ; exit 0 ;;
	00 | 0) clear ; exec menu ; exit 0 ;;
	x) exit 0 ;;
	*) echo -e "  ${R}Input is not valid!${N}" ; sleep 1 ; exec $0 ; exit 0 ;;
esac
exit 0
