#!/bin/bash
exit_clean() { echo " Dihentikan"; exit 0; }
trap exit_clean SIGINT
REPOKU="https://izin.vmessh.cloud"
REPOSC="https://iam.scvpn.cloud"
biji=`date +"%Y-%m-%d" -d "$dateFromServer"`
colornow=$(cat /etc/alawivpn/theme/color.conf)
NC="\e[0m"
R='\e[1;91m'
COLOR1="$(cat /etc/alawivpn/theme/$colornow | grep -w "TEXT" | cut -d: -f2|sed 's/ //g')"
COLBG1="$(cat /etc/alawivpn/theme/$colornow | grep -w "BG" | cut -d: -f2|sed 's/ //g')"
WH='\033[1;37m'
U=$COLOR1
O=$COLBG1
W=$WH
N=$NC
ipsaya=$(wget -qO- ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="${REPOKU}/registrasi.txt"
checking_sc() {
    useexp=$(curl -sS "$data_ip" | grep "$ipsaya" | awk '{print $3}')
    [[ "$date_list" > "$useexp" ]] && { systemctl stop nginx kyt xray ws-stunnel; dilarang; exit 1; }
}

checking_sc

author=$(cat /etc/profil)
lebar=54
judul="$author"
penyamaan() {
    lebar_judul=${#judul}
    peluasan=$(( (lebar - lebar_judul) /2 -1 ))
    padding=""
    for ((i=0; i<peluasan; i++)); do
        padding+=" "
    done
}
cetak_judul(){
    penyamaan
    if (( lebar_judul % 2 == 1 )); then
        printf " $U%s$N%s$W%s$N%s$U%s$N\n" "│" "$padding" "$judul" "$padding " "│"
    else
        printf " $U%s$N%s$W%s$N%s$U%s$N\n" "│" "$padding" "$judul" "$padding" "│"
    fi
}

# FUNGSIKU
garis() { echo -e " $U$*$N"; }
judul() { echo -e " $O$*$N"; }
tebal() { echo -e " $W$*$N"; }
kembali() { read -n 1 -s -r -p " Press any key to back on menu "; }

ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
author=$(cat /etc/profil)
TIMES="10"
CHATID=$(cat /etc/per/id)
KEY=$(cat /etc/per/token)
URL="https://api.telegram.org/bot$KEY/sendMessage"
domain=`cat /etc/xray/domain`
CHATID2=$(cat /etc/perlogin/id)
KEY2=$(cat /etc/perlogin/token)
URL2="https://api.telegram.org/bot$KEY2/sendMessage"
cd
if [ ! -e /etc/vless/akun ]; then
    mkdir -p /etc/vless/akun
fi
function add-vless(){
clear
    until [[ $user =~ ^[a-zA-Z0-9_.-]+$ && ${CLIENT_EXISTS} == '0' ]]; do
        echo -e "${U}╭═════════════════════════════════════════════════╮${N}"
        echo -e "${U}│${N}${O}            ${W}● Add Vless Account ●                ${N}${U}│ ${N}"
        echo -e "${U}╰═════════════════════════════════════════════════╯${N}"
        echo -e ""
        read -rp "User: " -e user
        CLIENT_EXISTS=$(grep -w $user /etc/xray/config.json | wc -l)
        if [[ ${CLIENT_EXISTS} == '1' ]]; then
            clear
            echo -e "${U}╭═════════════════════════════════════════════════╮${N}"
            echo -e "${U}│${N}${O}            ${W}● Add Vless Account ●                ${N}${U}│ ${N}"
            echo -e "${U}╰═════════════════════════════════════════════════╯${N}"
            echo -e "${U}╭═════════════════════════════════════════════════╮${N}"
            echo -e "${U}│                                                 │"
            echo -e "${U}│${W} Nama Duplikat Silahkan Buat Nama Lain.          ${U}│"
            echo -e "${U}│                                                 │"
            echo -e "${U}╰═════════════════════════════════════════════════╯${N}"
            read -n 1 -s -r -p "Press any key to back"
            add-vless
        fi
    done
    uuid=$(cat /proc/sys/kernel/random/uuid)
    until [[ $masaaktif =~ ^[0-9]+$ ]]; do
        read -p "Expired (hari): " masaaktif
    done
        until [[ $iplim =~ ^[0-9]+$ ]]; do
        read -p "Limit User (IP) or 0 Unlimited: " iplim
    done
    until [[ $Quota =~ ^[0-9]+$ ]]; do
        read -p "Limit User (GB) or 0 Unlimited: " Quota
    done
    if [ ! -e /etc/vless ]; then
        mkdir -p /etc/vless
    fi
    if [ ${iplim} = '0' ]; then
        iplim="999999999"
    fi
    if [ ${Quota} = '0' ]; then
        Quota="999999999"
    fi
    c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
    d=$((${c} * 1024 * 1024 * 1024))
    if [[ ${c} != "0" ]]; then
        echo "${d}" >/etc/vless/${user}
    fi
    echo "${iplim}" >/etc/vless/${user}IP
    exp=`date -d "$masaaktif days" +"%Y-%m-%d"`
    sed -i '/#vless$/a\#vl '"$user $exp $uuid"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
    sed -i '/#vlessgrpc$/a\#vlg '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
    vlesslink1="vless://${uuid}@${domain}:443?path=/vless&security=tls&encryption=none&host=${domain}&type=ws&sni=${domain}#${user}"
    vlesslink2="vless://${uuid}@${domain}:80?path=/vless&security=none&encryption=none&host=${domain}&type=ws#${user}"
    vlesslink3="vless://${uuid}@${domain}:443?mode=gun&security=tls&encryption=none&type=grpc&serviceName=vless-grpc&sni=${domain}#${user}"
    vless1="vless://${uuid}@${domain}:443?path=/vless%26security=tls%26encryption=none%26host=${domain}%26type=ws%26sni=${domain}#${user}"
    vless2="vless://${uuid}@${domain}:80?path=/vless%26security=none%26encryption=none%26host=${domain}%26type=ws#${user}"
    vless3="vless://${uuid}@${domain}:443?mode=gun%26security=tls%26encryption=none%26type=grpc%26serviceName=vless-grpc%26sni=${domain}#${user}"
    cat > /home/vps/public_html/vless-$user.txt <<-END
-------------------------------------------
Format Vless WS (CDN)
-------------------------------------------
- name: vless-$user-WS (CDN)
server: ${domain}
port: 443
type: vless
uuid: ${uuid}
cipher: auto
tls: true
skip-cert-verify: true
servername: ${domain}
network: ws
udp: true
ws-opts:
path: /vless
headers:
Host: ${domain}
-------------------------------------------
Format Vless WS (CDN) Non TLS
-------------------------------------------
- name: vless-$user-WS (CDN) Non TLS
server: ${domain}
port: 80
type: vless
uuid: ${uuid}
cipher: auto
tls: false
skip-cert-verify: false
servername: ${domain}
network: ws
ws-opts:
udp: true
path: /vless
headers:
Host: ${domain}
-------------------------------------------
Format Vless gRPC (SNI)
-------------------------------------------
- name: vless-$user-gRPC (SNI)
server: ${domain}
port: 443
type: vless
uuid: ${uuid}
cipher: auto
tls: true
skip-cert-verify: true
servername: ${domain}
network: grpc
grpc-opts:
grpc-mode: gun
grpc-service-name: vless-grpc
udp: true
-------------------------------------------
Link Vless Account
-------------------------------------------
Link TLS : vless://${uuid}@${domain}:443?path=/vless&security=tls&encryption=none&host=${domain}&type=ws&sni=${domain}#${user}
-------------------------------------------
Link none TLS : vless://${uuid}@${domain}:80?path=/vless&security=none&encryption=none&host=${domain}&type=ws#${user}
-------------------------------------------
Link GRPC : vless://${uuid}@${domain}:443?mode=gun&security=tls&encryption=none&type=grpc&serviceName=vless-grpc&sni=${domain}#${user}
-------------------------------------------
END
    if [ ${Quota} = '9999' ]; then
        TEXT="
━━━━━━━━━━━━━━━━━━━━━━━
Premium Vless Account
━━━━━━━━━━━━━━━━━━━━━━━
User         : ${user}
Domain       : <code>${domain}</code>
Login Limit  : ${iplim} IP
ISP          : ${ISP}
CITY         : ${CITY}
Port TLS     : 443
Port NTLS    : 80, 8080
Port GRPC    : 443
UUID         : <code>${uuid}</code>
AlterId      : 0
Security     : auto
Network      : WS or gRPC
Path vless   : <code>/vless</code>
ServiceName  : <code>/vless-grpc</code>
━━━━━━━━━━━━━━━━━━━━━━━
Link TLS     :
<code>${vless1}</code>
━━━━━━━━━━━━━━━━━━━━━━━
Link NTLS    :
<code>${vless2}</code>
━━━━━━━━━━━━━━━━━━━━━━━
Link gRPC    :
<code>${vless3}</code>
━━━━━━━━━━━━━━━━━━━━━━━
Format OpenClash :
http://$domain:89/vless-$user.txt
━━━━━━━━━━━━━━━━━━━━━━━
Expired Until    : $exp
━━━━━━━━━━━━━━━━━━━━━━━
$author
━━━━━━━━━━━━━━━━━━━━━━━
"
    else
        TEXT="
━━━━━━━━━━━━━━━━━━━━━━━
<b>    ☘️ Premium Vless Account ☘️</b>
━━━━━━━━━━━━━━━━━━━━━━━
<code>User         :</code> <code>${user}</code>
<code>Domain       :</code> <code>${domain}</code>
<code>Login Limit  :</code> <code>${iplim} IP</code>
<code>Quota Limit  :</code> <code>${Quota} GB</code>
<code>ISP          :</code> <code>${ISP}</code>
<code>CITY         :</code> <code>${CITY}</code>
<code>Port TLS     :</code> <code>443</code>
<code>Port NTLS    :</code> <code>80, 8080</code>
<code>Port GRPC    :</code> <code>443</code>
<code>UUID         :</code> <code>${uuid}</code>
<code>AlterId      :</code> <code>0</code>
<code>Security     :</code> <code>auto</code>
<code>Network      :</code> <code>WS or gRPC</code>
<code>Path vless   :</code> <code>/vless</code>
<code>ServiceName  :</code> <code>/vless-grpc</code>
━━━━━━━━━━━━━━━━━━━━━━━
<b>Link TLS     :</b>
<code>${vless1}</code>
━━━━━━━━━━━━━━━━━━━━━━━
<b>Link NTLS    :</b>
<code>${vless2}</code>
━━━━━━━━━━━━━━━━━━━━━━━
<b>Link GRPC    :</b>
<code>${vless3}</code>
━━━━━━━━━━━━━━━━━━━━━━━
<b>Format OpenClash :</b>
http://${domain}:89/vless-${user}.txt
━━━━━━━━━━━━━━━━━━━━━━━
<code>Expired Until :</code> <b>${exp}</b>
━━━━━━━━━━━━━━━━━━━━━━━
<b>${author}</b>
━━━━━━━━━━━━━━━━━━━━━━━

"
    fi
    curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
    cd
    if [ ! -e /etc/tele ]; then
        echo -ne
    else
        echo "$TEXT" > /etc/notiftele
        bash /etc/tele
    fi
    user2=$(echo "$user" | cut -c 1-3)
    TIME2=$(date +'%Y-%m-%d %H:%M:%S')
    TEXT2="
━━━━━━━━━━━━━━━━━━━━━━━
<b>     ☘ VLESS PREMIUM SOLD ☘</b>
━━━━━━━━━━━━━━━━━━━━━━━
<code>Order  :</code> <code>VLESS Premium</code>
<code>User   :</code> <code>${user2}⬤⬤⬤</code>
<code>Domain :</code> <code>${domain}</code>
<code>ISP    :</code> <code>${ISP}</code>
<code>CITY   :</code> <code>$CITY</code>
<code>Date   :</code> <code>${TIME2} WIB</code>
<code>Limit  :</code> <code>${iplim} IP</code>
<code>Aktif  :</code> <code>$masaaktif Hari</code>
━━━━━━━━━━━━━━━━━━━━━━━
<i>Succes create this vless account..</i>"
    curl -s --max-time $TIMES -d "chat_id=$CHATID2&disable_web_page_preview=1&text=$TEXT2&parse_mode=html" $URL2 >/dev/null
    clear
    echo -e "${U} ━━━━━━━━━━━━━━━━━━━━━━━ ${N}" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${W}● Premium Vless Account ●" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ━━━━━━━━━━━━━━━━━━━━━━━ ${N}" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${W}User         ${U}: ${W}${user}" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${W}ISP          ${U}: ${W}$ISP" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${W}City         ${U}: ${W}$CITY" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${W}Domain       ${U}: ${W}${domain}" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${W}Login Limit  ${U}: ${W}${iplim} IP" | tee -a /etc/vless/akun/log-create-${user}.log
    if [ ${Quota} = '9999' ]; then
        echo -ne
    else
        echo -e "${U} ${N} ${W}Quota Limit  ${U}: ${W}${Quota} GB" | tee -a /etc/vless/akun/log-create-${user}.log
    fi
    echo -e "${U} ${N} ${W}Port TLS     ${U}: ${W}443" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${W}Port NTLS    ${U}: ${W}80,8080" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${W}Port gRPC    ${U}: ${W}443" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${W}UUID         ${U}: ${W}${uuid}" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${W}Encryption   ${U}: ${W}none" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${W}Network      ${U}: ${W}ws" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${W}Path         ${U}: ${W}/vless" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${W}Path grpc    ${U}: ${W}/vless-grpc" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ━━━━━━━━━━━━━━━━━━━━━━━ ${N}" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${U}Link Websocket TLS      ${W}:${N}" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U}${N}${W}${vlesslink1}${N}"  | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ━━━━━━━━━━━━━━━━━━━━━━━ ${N}" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${U}Link Websocket NTLS  ${W}:${N}" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U}${N}${W}${vlesslink2}${N}"  | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ━━━━━━━━━━━━━━━━━━━━━━━ ${N}" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${U}Link gRPC               ${W}:${N}" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U}${N}${W}${vlesslink3}${N}"  | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ━━━━━━━━━━━━━━━━━━━━━━━ ${N}" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${W}Format Openclash ${U}: " | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${W}http://$domain:89/vless-$user.txt${N}" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ━━━━━━━━━━━━━━━━━━━━━━━ ${N}" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${W}Expired Until   ${U}: ${W}$exp" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ━━━━━━━━━━━━━━━━━━━━━━━ ${N}" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${W}    $author    " | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ━━━━━━━━━━━━━━━━━━━━━━━ ${N}" | tee -a /etc/vless/akun/log-create-${user}.log
    echo | tee -a /etc/vless/akun/log-create-${user}.log
    systemctl restart xray > /dev/null 2>&1
    bottelegram > /dev/null 2>&1 &
    kembali
    exec menu && exit 0
}

function trial-vless(){
clear
    cd
    echo -e "${U}╭═════════════════════════════════════════════════╮${N}"
    echo -e "${U} ${N}${O}            ${W}● Trial Vless Account ●             "
    echo -e "${U}╰═════════════════════════════════════════════════╯${N}"
    until [[ $timer =~ ^[0-9]+$ ]]; do
    read -p "Expired (Minutes): " timer
    done
    user=Trial-`</dev/urandom tr -dc X-Z0-9 | head -c4`
    uuid=$(cat /proc/sys/kernel/random/uuid)
    masaaktif=0
    iplim=1
    Quota=10
    if [ ! -e /etc/vless ]; then
    mkdir -p /etc/vless
    fi
    c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
    d=$((${c} * 1024 * 1024 * 1024))
    if [[ ${c} != "0" ]]; then
    echo "${d}" >/etc/vless/${user}
    fi
    echo "${iplim}" > /etc/vless/${user}IP
    ecp=$(date -d "+$timer minutes" +"%Y-%m-%d %H:%M:%S")
    exp=$(echo $ecp | awk '{print $1}')
    touch /etc/xray/trialvless
    echo -e "### $user $ecp" >> /etc/xray/trialvless
sed -i '/#vless$/a\#vl '"$user $exp $uuid"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#vlessgrpc$/a\#vlg '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
    vlesslink1="vless://${uuid}@${domain}:443?path=/vless&security=tls&encryption=none&host=${domain}&type=ws&sni=${domain}#${user}"
    vlesslink2="vless://${uuid}@${domain}:80?path=/vless&security=none&encryption=none&host=${domain}&type=ws#${user}"
    vlesslink3="vless://${uuid}@${domain}:443?mode=gun&security=tls&encryption=none&type=grpc&serviceName=vless-grpc&sni=${domain}#${user}"
    vless1="vless://${uuid}@${domain}:443?path=/vless%26security=tls%26encryption=none%26host=${domain}%26type=ws%26sni=${domain}#${user}"
    vless2="vless://${uuid}@${domain}:80?path=/vless%26security=none%26encryption=none%26host=${domain}%26type=ws#${user}"
    vless3="vless://${uuid}@${domain}:443?mode=gun%26security=tls%26encryption=none%26type=grpc%26serviceName=vless-grpc%26sni=${domain}#${user}"
    clear
    cat > /home/vps/public_html/vless-$user.txt <<-END
-------------------------------------------
Format Vless WS (CDN)
-------------------------------------------
- name: vless-$user-WS (CDN)
server: ${domain}
port: 443
type: vless
uuid: ${uuid}
cipher: auto
tls: true
skip-cert-verify: true
servername: ${domain}
network: ws
udp: true
ws-opts:
path: /vless
headers:
Host: ${domain}
-------------------------------------------
Format Vless WS (CDN) Non TLS
-------------------------------------------
- name: vless-$user-WS (CDN) Non TLS
server: ${domain}
port: 80
type: vless
uuid: ${uuid}
cipher: auto
tls: false
skip-cert-verify: false
servername: ${domain}
network: ws
ws-opts:
udp: true
path: /vless
headers:
Host: ${domain}
-------------------------------------------
Format Vless gRPC (SNI)
-------------------------------------------
- name: vless-$user-gRPC (SNI)
server: ${domain}
port: 443
type: vless
uuid: ${uuid}
cipher: auto
tls: true
skip-cert-verify: true
servername: ${domain}
network: grpc
grpc-opts:
grpc-mode: gun
grpc-service-name: vless-grpc
udp: true
-------------------------------------------
Link Vless Account
-------------------------------------------
Link TLS : vless://${uuid}@${domain}:443?path=/vless&security=tls&encryption=none&host=${domain}&type=ws&sni=${domain}#${user}
-------------------------------------------
Link NTLS : vless://${uuid}@${domain}:80?path=/vless&security=none&encryption=none&host=${domain}&type=ws#${user}
-------------------------------------------
Link gRPC : vless://${uuid}@${domain}:443?mode=gun&security=tls&encryption=none&type=grpc&serviceName=vless-grpc&sni=${domain}#${user}
-------------------------------------------
END
    TEXT="
━━━━━━━━━━━━━━━━━━━━━━━
<b>☘️ Trial Premium Vless Account ☘️</b>
━━━━━━━━━━━━━━━━━━━━━━━
<code>User         :</code> <code>${user}</code>
<code>Domain       :</code> <code>${domain}</code>
<code>Login Limit  :</code> <code>${iplim} IP</code>
<code>ISP          :</code> <code>${ISP}</code>
<code>CITY         :</code> <code>${CITY}</code>
<code>Port TLS     :</code> <code>443</code>
<code>Port NTLS    :</code> <code>80, 8080</code>
<code>Port GRPC    :</code> <code>443</code>
<code>UUID         :</code> <code>${uuid}</code>
<code>AlterId      :</code> <code>0</code>
<code>Security     :</code> <code>auto</code>
<code>Network      :</code> <code>WS or gRPC</code>
<code>Path vless   :</code> <code>/vless</code>
<code>ServiceName  :</code> <code>/vless-grpc</code>
━━━━━━━━━━━━━━━━━━━━━━━
<b>Link TLS     :</b>
<code>${vless1}</code>
━━━━━━━━━━━━━━━━━━━━━━━
<b>Link NTLS    :</b>
<code>${vless2}</code>
━━━━━━━━━━━━━━━━━━━━━━━
<b>Link GRPC    :</b>
<code>${vless3}</code>
━━━━━━━━━━━━━━━━━━━━━━━
<b>Format OpenClash :</b>
http://${domain}:89/vless-${user}.txt
━━━━━━━━━━━━━━━━━━━━━━━
<code>Expired :</code> <b>${ecp}</b>
━━━━━━━━━━━━━━━━━━━━━━━
<b>${author}</b>
━━━━━━━━━━━━━━━━━━━━━━━

"
    curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
    cd
    if [ ! -e /etc/tele ]; then
        echo -ne
    else
        echo "$TEXT" > /etc/notiftele
        bash /etc/tele
    fi
    clear
    echo -e "${U} ━━━━━━━━━━━━━━━━━━━━━━━ ${N}" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${W}● Trial Premium Vless Account ●" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ━━━━━━━━━━━━━━━━━━━━━━━ ${N}" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${W}User         ${U}: ${W}${user}" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${W}ISP          ${U}: ${W}$ISP" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${W}City         ${U}: ${W}$CITY" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${W}Domain       ${U}: ${W}${domain}" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${W}Login Limit  ${U}: ${W}${iplim} IP" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${W}Port TLS     ${U}: ${W}443" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${W}Port NTLS    ${U}: ${W}80,8080" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${W}Port gRPC    ${U}: ${W}443" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${W}UUID         ${U}: ${W}${uuid}" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${W}Encryption   ${U}: ${W}none" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${W}Network      ${U}: ${W}ws" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${W}Path         ${U}: ${W}/vless" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${W}Path grpc    ${U}: ${W}/vless-grpc" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ━━━━━━━━━━━━━━━━━━━━━━━ ${N}" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${U}Link Websocket TLS      ${W}:${N}" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U}${N}${W}${vlesslink1}${N}"  | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ━━━━━━━━━━━━━━━━━━━━━━━ ${N}" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${U}Link Websocket NTLS  ${W}:${N}" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U}${N}${W}${vlesslink2}${N}"  | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ━━━━━━━━━━━━━━━━━━━━━━━ ${N}" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${U}Link gRPC               ${W}:${N}" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U}${N}${W}${vlesslink3}${N}"  | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ━━━━━━━━━━━━━━━━━━━━━━━ ${N}" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${W}Format Openclash ${U}: " | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${W}http://$domain:89/vless-$user.txt${N}" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ━━━━━━━━━━━━━━━━━━━━━━━ ${N}" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${W}Expired  ${U}: ${W}$ecp" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ━━━━━━━━━━━━━━━━━━━━━━━ ${N}" | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ${N} ${W}    $author    " | tee -a /etc/vless/akun/log-create-${user}.log
    echo -e "${U} ━━━━━━━━━━━━━━━━━━━━━━━ ${N}" | tee -a /etc/vless/akun/log-create-${user}.log
    echo | tee -a /etc/vless/akun/log-create-${user}.log
    systemctl restart xray > /dev/null 2>&1
    kembali
    exec menu && exit 0
}

function limit-vless(){
    clear
    NUMBER_OF_CLIENTS=$(grep -c -E "^#vlg " "/etc/xray/config.json")
    if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
        clear
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        judul "      ◈ Limit Vless Account ◈      "
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo
        tebal "          Tidak ada user!!"
        echo
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo
        kembali
        exec $0 && exit 0
    fi
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    judul "      ◈ Limit Vless Account ◈      "
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    tebal "Please choose the client to change ip"
    tebal "ketik [0] kembali ke menu"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    printf "${W}  %-5s %-15s %s\n" "No" "Name" "Expired"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    grep -E "^#vlg " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | nl -s ') ' | while read -r line; do
        number=$(echo "$line" | cut -d')' -f 1 | xargs); name=$(echo "$line" | cut -d' ' -f 2); expired=$(echo "$line" | cut -d' ' -f 3-)
        printf "  %-5s %-15s %s\n" "$number" "$name" "$expired"
    done
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
        if [[ ${CLIENT_NUMBER} == '1' ]]; then
            read -rp " Select one client [1]: " CLIENT_NUMBER
        else
            read -rp " Select one client [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER
            if [[ ${CLIENT_NUMBER} == '0' ]]; then
                exec $0 && exit 0
            fi
        fi
    done
    clear
    until [[ $iplim =~ ^[0-9]+$ ]]; do
        read -p "Limit User (IP) or 0 Unlimited: " iplim
    done
    until [[ $Quota =~ ^[0-9]+$ ]]; do
        read -p "Limit User (GB) or 0 Unlimited: " Quota
    done
    if [ ! -e /etc/vless ]; then
        mkdir -p /etc/vless
    fi
    if [ ${iplim} = '0' ]; then
        iplim="999999999"
    fi
    if [ ${Quota} = '0' ]; then
    Quota="999999999"
        fi
    user=$(grep -E "^#vlg " "/etc/xray/config.json" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
    c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
    d=$((${c} * 1024 * 1024 * 1024))
    echo "${iplim}" >/etc/vless/${user}IP
    if [[ ${c} != "0" ]]; then
        echo "${d}" >/etc/vless/${user}
    fi
    TEXT="
━━━━━━━━━━━━━━━━━━━━━━━
<b>☘️ XRAY VLESS IP LIMIT ☘️</b>
━━━━━━━━━━━━━━━━━━━━━━━
<code>User    :</code> <code>$user</code>
<code>Domain  :</code> <code>${domain}</code>
<code>ISP     :</code> <code>$ISP</code>
<code>CITY    :</code> <code>$CITY</code>
<code>New Limit IP :</code> <code>$iplim IP</code>
<code>New Limit Quota :</code> <code>$Quota GB</code>
━━━━━━━━━━━━━━━━━━━━━━━
<i>Succes Change Limit This Account...</i>
"
    curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
    cd
    if [ ! -e /etc/tele ]; then
        echo -ne
    else
        echo "$TEXT" > /etc/notiftele
        bash /etc/tele
    fi
    clear
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo " VLESS Account Was Successfully Change Limit IP"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo
    echo " Client Name : $user"
    echo " Limit IP    : $iplim IP"
    echo " Limit Quota : $Quota GB"
    echo
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo
    bottelegram > /dev/null 2>&1 &
    kembali
    exec $0 && exit 0
}

function renew-vless(){
clear
    NUMBER_OF_CLIENTS=$(grep -c -E "^#vl " "/etc/xray/config.json")
    if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
        clear
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        judul "      ◈ Renew Vless Account ◈      "
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo
        tebal "          Tidak ada user!!"
        echo
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo
        kembali
        exec $0 && exit 0
    fi
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    judul "      ◈ Renew Vless Account ◈      "
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    tebal "Please choose the client to renew"
    tebal "ketik [0] kembali ke menu"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    printf "${W}  %-5s %-15s %s\n" "No" "Name" "Expired"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    grep -E "^#vl " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | nl -s ') ' | while read -r line; do
        number=$(echo "$line" | cut -d')' -f 1 | xargs); name=$(echo "$line" | cut -d' ' -f 2); expired=$(echo "$line" | cut -d' ' -f 3-)
        printf "  %-5s %-15s %s\n" "$number" "$name" "$expired"
    done
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
        if [[ ${CLIENT_NUMBER} == '1' ]]; then
            read -rp " Select one client [1]: " CLIENT_NUMBER
        else
            read -rp " Select one client [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER
            if [[ ${CLIENT_NUMBER} == '0' ]]; then
                exec $0 && exit 0
            fi
        fi
    done
    read -p " Days ektend: " masaaktif
    user=$(grep -E "^#vl " "/etc/xray/config.json" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
    exp=$(grep -E "^#vl " "/etc/xray/config.json" | cut -d ' ' -f 3 | sed -n "${CLIENT_NUMBER}"p)
    now=$(date +%Y-%m-%d)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    exp2=$(( (d1 - d2) / 86400 ))
    exp3=$(($exp2 + $masaaktif))
    exp4=`date -d "$exp3 days" +"%Y-%m-%d"`
    sed -i "s/#vl $user $exp/#vl $user $exp4/g" /etc/xray/config.json
    sed -i "s/#vlg $user $exp/#vlg $user $exp4/g" /etc/xray/config.json
    clear
    TEXT="
━━━━━━━━━━━━━━━━━━━━━━━
<b>☘️ XRAY VLESS RENEW ☘️</b>
━━━━━━━━━━━━━━━━━━━━━━━
<code>User    :</code> <code>$user</code>
<code>Domain  :</code> <code>${domain}</code>
<code>ISP     :</code> <code>$ISP</code>
<code>CITY    :</code> <code>$CITY</code>
<code>Expired :</code> <code>$exp4</code>
━━━━━━━━━━━━━━━━━━━━━━━
<i>Succes Renew This Account..</i>
"
    curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
    cd
    if [ ! -e /etc/tele ]; then
        echo -ne
    else
        echo "$TEXT" > /etc/notiftele
        bash /etc/tele
    fi
    user2=$(echo "$user" | cut -c 1-3)
    TIME2=$(date +'%Y-%m-%d %H:%M:%S')
    TEXT2="
━━━━━━━━━━━━━━━━━━━━━━━
<b>     ☘ VLESS PREMIUM SOLD ☘</b>
━━━━━━━━━━━━━━━━━━━━━━━
<code>Order  :</code> <code>VLESS Premium</code>
<code>User   :</code> <code>${user2}⬤⬤⬤</code>
<code>Domain :</code> <code>${domain}</code>
<code>ISP    :</code> <code>$ISP</code>
<code>CITY   :</code> <code>$CITY</code>
<code>Date   :</code> <code>${TIME2} WIB</code>
<code>Aktif  :</code> <code>$masaaktif Hari</code>
━━━━━━━━━━━━━━━━━━━━━━━
<i>Succes Renew This Account...</i>
"
    curl -s --max-time $TIMES -d "chat_id=$CHATID2&disable_web_page_preview=1&text=$TEXT2&parse_mode=html" $URL2 >/dev/null
    clear
    systemctl restart xray > /dev/null 2>&1
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo " VLESS Account Was Successfully Renewed"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo
    echo " Client Name : $user"
    echo " Expired On  : $exp4"
    echo
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo
    bottelegram > /dev/null 2>&1 &
    kembali
    exec $0 && exit 0
}

function del-vless(){
    clear
    NUMBER_OF_CLIENTS=$(grep -c -E "^#vl " "/etc/xray/config.json")
    if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        judul "      ◈ Delete Vless Account ◈     "
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo
        tebal "          Tidak ada user!!"
        echo
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        kembali
        exec $0 && exit 0
    fi
    clear
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    judul "      ◈ Delete Vless Account ◈     "
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    tebal "Please choose the client to remove"
    tebal "ketik [0] kembali ke menu"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    printf "${W}  %-5s %-15s %s\n" "No" "Name" "Expired"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    grep -E "^#vl " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | nl -s ') ' | while read -r line; do
        number=$(echo "$line" | cut -d')' -f 1 | xargs); name=$(echo "$line" | cut -d' ' -f 2); expired=$(echo "$line" | cut -d' ' -f 3-)
        printf "  %-5s %-15s %s\n" "$number" "$name" "$expired"
    done
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
        if [[ ${CLIENT_NUMBER} == '1' ]]; then
            read -rp " Select one client [1]: " CLIENT_NUMBER
        else
            read -rp " Select one client [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER
            if [[ ${CLIENT_NUMBER} == '0' ]]; then
                exec $0 && exit 0
            fi
        fi
    done
    user=$(grep -E "^#vl " "/etc/xray/config.json" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
    exp=$(grep -E "^#vl " "/etc/xray/config.json" | cut -d ' ' -f 3 | sed -n "${CLIENT_NUMBER}"p)
    uuid=$(grep -E "^#vl " "/etc/xray/config.json" | cut -d ' ' -f 4 | sed -n "${CLIENT_NUMBER}"p)
    if [ ! -e /etc/vless/akundelete ]; then
        echo > /etc/vless/akundelete
    fi
    clear
    echo "### $user $exp $uuid" >> /etc/vless/akundelete
    sed -i "/^#vl $user $exp/,/^},{/d" /etc/xray/config.json
    sed -i "/^#vlg $user $exp/,/^},{/d" /etc/xray/config.json
    clear
    clear
    rm /etc/vless/${user}IP >/dev/null 2>&1
    rm /home/vps/public_html/vless-$user.txt >/dev/null 2>&1
    rm /etc/vless/${user}login >/dev/null 2>&1
    systemctl restart xray > /dev/null 2>&1
    clear
    TEXT="
━━━━━━━━━━━━━━━━━━━━━━━
<b>☘️ XRAY VLESS DELETE ☘️</b>
━━━━━━━━━━━━━━━━━━━━━━━
<code>User    :</code> <code>$user</code>
<code>Domain  :</code> <code>${domain}</code>
<code>ISP     :</code> <code>$ISP</code>
<code>CITY    :</code> <code>$CITY</code>
<code>Expired :</code> <code>$exp</code>
━━━━━━━━━━━━━━━━━━━━━━━
<i>Succes Delete This Account...</i>
"
    curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
    cd
    if [ ! -e /etc/tele ]; then
        echo -ne
    else
        echo "$TEXT" > /etc/notiftele
        bash /etc/tele
    fi
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    judul " Vless Account Deleted Successfully"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo " Client Name : $user"
    echo " Expired On  : $exp"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo
    kembali
    exec $0 && exit 0
}

tim2sec() {
    mult=1
    arg="$1"
    inu=0
    while [ ${#arg} -gt 0 ]; do
        prev="${arg%:*}"
        if [ "$prev" = "$arg" ]; then
            curr="${arg#0}"
            prev=""
        else
            curr="${arg##*:}"
            curr="${curr#0}"
        fi
        curr="${curr%.*}"
        inu=$((inu + curr * mult))
        mult=$((mult * 60))
        arg="$prev"
    done
    echo "$inu"
}
function convert() {
    local -i bytes=$1
    if [[ $bytes -lt 1024 ]]; then
        echo "${bytes} B"
    elif [[ $bytes -lt 1048576 ]]; then
        echo "$(awk "BEGIN {printf \"%.2f\", $bytes/1024}" | sed 's/\.00$//' | sed 's/\.\([0-9]\)0$/.\1/') KB"
    elif [[ $bytes -lt 1073741824 ]]; then
        echo "$(awk "BEGIN {printf \"%.2f\", $bytes/1048576}" | sed 's/\.00$//' | sed 's/\.\([0-9]\)0$/.\1/') MB"
    else
        echo "$(awk "BEGIN {printf \"%.2f\", $bytes/1073741824}" | sed 's/\.00$//' | sed 's/\.\([0-9]\)0$/.\1/') GB"
    fi
}

function cek-vless(){
    clear
    xrayy=$(cat /var/log/xray/access.log | wc -l)
    if [[ xrayy -le 5 ]]; then
        systemctl restart xray
    fi
    xraylimit
    echo -e " ${U}╭═════════════════════════════════════════════════╮${N}"
    echo -e " ${U}│${N}${O}             ${W}● VLESS USER ONLINE ●               ${N}${U}│ ${N}"
    echo -e " ${U}╰═════════════════════════════════════════════════╯${N}"
    echo -e " ${U}╭═════════════════════════════════════════════════╮${N}"
    vl=($(cat /etc/xray/config.json | grep "^#vlg" | awk '{print $2}' | sort -u))
    echo -n >/tmp/vl
    for db1 in ${vl[@]}; do
        logvl=$(cat /var/log/xray/access.log | grep -w "email: ${db1}" | tail -n 100)
        while read a; do
            if [[ -n ${a} ]]; then
                set -- ${a}
                ina="${7}"
                inu="${2}"
                anu="${3}"
                enu=$(echo "${anu}" | sed 's/tcp://g' | sed '/^$/d' | cut -d. -f1,2,3)
                now=$(tim2sec ${timenow})
                client=$(tim2sec ${inu})
                nowt=$(((${now} - ${client})))
                if [[ ${nowt} -lt 40 ]]; then
                    cat /tmp/vl | grep -w "${ina}" | grep -w "${enu}" >/dev/null
                    if [[ $? -eq 1 ]]; then
                        echo "${ina} ${inu} WIB : ${enu}" >>/tmp/vl
                        splvl=$(cat /tmp/vl)
                    fi
                fi
            fi
        done <<<"${logvl}"
    done
    if [[ ${splvl} != "" ]]; then
        printf " ${U}%-5s${W}%-15s%-12s%-12s%-8s${U}%s\n" "│" "USERNAME" "LOGIN" "USAGE" "LIMIT" "│"
        echo -e " ${U}├═════════════════════════════════════════════════┤${N}"
        for vluser in ${vl[@]}; do
            vlhas=$(cat /tmp/vl | grep -w "${vluser}" | wc -l)
            tess=0
            if [[ ${vlhas} -gt $tess ]]; then
                byt=$(cat /etc/limit/vless/${vluser})
                gb=$(convert ${byt})
                lim=$(cat /etc/vless/${vluser})
                lim2=$(convert ${lim})
                printf " ${U}%-5s\e[0;33m%-17s%-10s%-12s%-8s${U}%s\n" "│" "$vluser" "$vlhas" "$gb" "$lim2" "│"
            fi
        done
    else
        echo -e " ${U}│                                                 │"
        echo -e " ${U}│${W}             TIDAK ADA USER ONLINE!              ${U}│${N}"
        echo -e " ${U}│                                                 │"
        echo -e " ${U}╰═════════════════════════════════════════════════╯${N}"
        read -n 1 -s -r -p "  Press any key to back on menu"
        exec menu && exit 0
    fi

    echo -e " ${U}╰═════════════════════════════════════════════════╯${N}"
    echo -e " ${U}╭═════════════════════════════════════════════════╮${N}"
    echo -e " ${U}│${W}          CODE BY : ALAWI CONFIG-SANTRI          ${U}│${N}"
    echo -e " ${U}╰═════════════════════════════════════════════════╯${N}"
    echo
    read -n 1 -s -r -p "   Press any key to back on menu"
    exec $0 && exit 0
}
function list-vless(){
    clear
    NUMBER_OF_CLIENTS=$(grep -c -E "^#vl " "/etc/xray/config.json")
    if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        judul "      ◈ Config Vless Account ◈     "
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo
        tebal "          Tidak ada user!!"
        echo
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        kembali
        exec $0 && exit 0
    fi
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    judul "      ◈ Config Vless Account ◈     "
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    tebal "Please choose the client to view the config"
    tebal "ketik [0] kembali ke menu"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    printf "${W}  %-5s %-15s %s\n" "No" "Name" "Expired"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    grep -E "^#vl " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | nl -s ') ' | while read -r line; do
        number=$(echo "$line" | cut -d')' -f 1 | xargs); name=$(echo "$line" | cut -d' ' -f 2); expired=$(echo "$line" | cut -d' ' -f 3-)
        printf "  %-5s %-15s %s\n" "$number" "$name" "$expired"
    done
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

    until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
        if [[ ${CLIENT_NUMBER} == '1' ]]; then
            read -rp " Select one client [1]: " CLIENT_NUMBER
        else
            read -rp " Select one client [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER
            if [[ ${CLIENT_NUMBER} == '0' ]]; then
                exec $0 && exit 0
            fi
        fi
    done
    clear
    user=$(grep -E "^#vl " "/etc/xray/config.json" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
    cat /etc/vless/akun/log-create-${user}.log
    cat /etc/vless/akun/log-create-${user}.log > /etc/notifakun
    sed -i 's/\x1B\[1;37m//g' /etc/notifakun
    sed -i 's/\x1B\[0;96m//g' /etc/notifakun
    sed -i 's/\x1B\[0m//g' /etc/notifakun
    TEXT=$(cat /etc/notifakun)
    curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
    cd
    if [ ! -e /etc/tele ]; then
        echo -ne
    else
        echo "$TEXT" > /etc/notiftele
        bash /etc/tele
    fi
    kembali
    exec $0 && exit 0
}

function login-vless(){
    clear
    echo -e "${U}╭═══════════════════════════════════════════════╮${N}"
    echo -e "${U}│${N}${O}           ${W}● SETTING MULTI LOGIN ●             ${N}${U}│ ${N}"
    echo -e "${U}╰═══════════════════════════════════════════════╯${N}"
    echo -e "${U}╭═══════════════════════════════════════════════╮${N}"
    echo -e "${U}│ ${N} SILAHKAN TULIS JUMLAH NOTIFIKASI UNTUK LOCK    ${N}"
    echo -e "${U}│ ${N} AKUN USER YANG MULTI LOGIN     ${N}"
    echo -e "${U}╰═══════════════════════════════════════════════╯${N}"
    read -rp "   Jika Mau 3x Notif baru kelock tulis 3, dst: " -e notif
    cd /etc/vless
    echo "$notif" > notif
    clear
    echo -e "${U}╭═══════════════════════════════════════════════╮${N}"
    echo -e "${U}│${N}${O}           ${W}● SETTING MULTI LOGIN ●             ${N}${U}│ ${N}"
    echo -e "${U}╰═══════════════════════════════════════════════╯${N}"
    echo -e "${U}╭═══════════════════════════════════════════════╮${N}"
    echo -e "${U}│ ${N} SUCCES GANTI NOTIF LOCK JADI $notif ${N} "
    echo -e "${U}╰═══════════════════════════════════════════════╯${N}"
    exec $0 && exit 0
}
function lock-vless(){
    cd
    clear
    if [ ! -e /etc/vless/listlock ]; then
        echo > /etc/vless/listlock
    fi
    NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/vless/listlock")
    if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        judul "      ◈ Unlock Vless Account ◈     "
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo
        tebal "          Tidak ada user!!"
        echo
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        kembali
        exec $0 && exit 0
    fi
    clear
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    judul "      ◈ Unlock Vless Account ◈     "
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    tebal "Please choose the client to Unlock"
    tebal "ketik [0] kembali ke menu"
    tebal "ketik [999] untuk delete semua Akun"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    printf "${W}  %-5s %-15s %s\n" "No" "Name" "Expired"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    grep -E "^### " "/etc/vless/listlock" | cut -d ' ' -f 2-3 | nl -s ') ' | while read -r line; do
        number=$(echo "$line" | cut -d')' -f 1 | xargs); name=$(echo "$line" | cut -d' ' -f 2); expired=$(echo "$line" | cut -d' ' -f 3-)
        printf "  %-5s %-15s %s\n" "$number" "$name" "$expired"
    done
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
        if [[ ${CLIENT_NUMBER} == '1' ]]; then
            read -rp " Select one client [1]: " CLIENT_NUMBER
        else
            read -rp " Select one client [1-${NUMBER_OF_CLIENTS}] to Unlock: " CLIENT_NUMBER
            if [[ ${CLIENT_NUMBER} == '0' ]]; then
                exec $0 && exit 0
            fi
            if [[ ${CLIENT_NUMBER} == '999' ]]; then
                rm /etc/vless/listlock
                exec $0 && exit 0
            fi
        fi
    done
    user=$(grep -E "^### " "/etc/vless/listlock" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
    exp=$(grep -E "^### " "/etc/vless/listlock" | cut -d ' ' -f 3 | sed -n "${CLIENT_NUMBER}"p)
    uuid=$(grep -E "^### " "/etc/vless/listlock" | cut -d ' ' -f 4 | sed -n "${CLIENT_NUMBER}"p)
    sed -i '/#vless$/a\#vl '"$user $exp $uuid"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
    sed -i '/#vlessgrpc$/a\#vlg '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
    sed -i "/^### $user $exp $uuid/d" /etc/vless/listlock
    systemctl restart xray
    TEXT="
━━━━━━━━━━━━━━━━━━━━━━━
<b>☘️ XRAY VLESS UNLOCK ☘️</b>
━━━━━━━━━━━━━━━━━━━━━━━
<code>User    :</code> <code>$user</code>
<code>Domain  :</code> <code>${domain}</code>
<code>ISP     :</code> <code>$ISP</code>
<code>CITY    :</code> <code>$CITY</code>
<code>Expired :</code> <code>$exp</code>
━━━━━━━━━━━━━━━━━━━━━━━
<i>Succes Unlock This Account...</i>
"
    curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
    cd
    if [ ! -e /etc/tele ]; then
        echo -ne
    else
        echo "$TEXT" > /etc/notiftele
        bash /etc/tele
    fi
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    judul " Vless Account Unlock Successfully "
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo " Client Name : $user"
    echo " Status      : Unlocked"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo
    bottelegram > /dev/null 2>&1 &
    kembali
    exec $0 && exit 0
}

function res-user(){
    clear
    cd
    if [ ! -e /etc/vless/akundelete ]; then
        echo > /etc/vless/akundelete
    fi
    clear
    NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/vless/akundelete")
    if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        judul "     ◈ Restore Vless Account ◈     "
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo
        tebal "          Tidak ada user!!"
        echo
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        kembali
        exec $0 && exit 0
    fi
    clear
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    judul "     ◈ Restore Vless Account ◈     "
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    tebal "Please choose the client to Restore"
    tebal "ketik [0] kembali ke menu"
    tebal "ketik [999] untuk delete semua Akun"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    printf "${W}  %-5s %-15s %s\n" "No" "Name" "Expired"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    grep -E "^### " "/etc/vless/akundelete" | cut -d ' ' -f 2-3 | nl -s ') ' | while read -r line; do
        number=$(echo "$line" | cut -d')' -f 1 | xargs); name=$(echo "$line" | cut -d' ' -f 2); expired=$(echo "$line" | cut -d' ' -f 3-)
        printf "  %-5s %-15s %s\n" "$number" "$name" "$expired"
    done
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
        if [[ ${NUMBER_OF_CLIENTS} == '1' ]]; then
            read -rp " Select one client [1]: " CLIENT_NUMBER
            if [[ ${CLIENT_NUMBER} == '0' ]]; then exec $0 && exit 0; fi
            if [[ ${CLIENT_NUMBER} == '999' ]]; then rm /etc/vless/akundelete; exec $0 && exit 0; fi
        else
            read -rp " Select one client [1-${NUMBER_OF_CLIENTS}] to Unlock: " CLIENT_NUMBER
            if [[ ${CLIENT_NUMBER} == '0' ]]; then exec $0 && exit 0; fi
            if [[ ${CLIENT_NUMBER} == '999' ]]; then rm /etc/vless/akundelete; exec $0 && exit 0; fi
        fi
    done
    until [[ $masaaktif =~ ^[0-9]+$ ]]; do
        read -p " Expired (days): " masaaktif
    done
    until [[ $iplim =~ ^[0-9]+$ ]]; do
        read -p " Limit User (IP) or 0 Unlimited: " iplim
    done
    until [[ $Quota =~ ^[0-9]+$ ]]; do
        read -p " Limit Quota (GB) or 0 Unlimited: " Quota
    done
    if [ ${iplim} = '0' ]; then
        iplim="999999999"
    fi
    if [ ${Quota} = '0' ]; then
        Quota="999999999"
    fi
    user=$(grep -E "^### " "/etc/vless/akundelete" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
    exp=$(grep -E "^### " "/etc/vless/akundelete" | cut -d ' ' -f 3 | sed -n "${CLIENT_NUMBER}"p)
    uuid=$(grep -E "^### " "/etc/vless/akundelete" | cut -d ' ' -f 4 | sed -n "${CLIENT_NUMBER}"p)
    newdate=$(date -d "$masaaktif days" +"%Y-%m-%d")
    sed -i '/#vless$/a\#vl '"$user $newdate $uuid"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
    sed -i '/#vlessgrpc$/a\#vlg '"$user $newdate"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
    echo "${iplim}" >/etc/vless/${user}IP
    c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
    d=$((${c} * 1024 * 1024 * 1024))
    if [[ ${c} != "0" ]]; then
        echo "${d}" >/etc/vless/${user}
    fi
    sed -i "/^### ${user} ${exp} ${uuid}/d" /etc/vless/akundelete
    systemctl restart xray
TEXT="
━━━━━━━━━━━━━━━━━━━━━━━
<b>☘️ XRAY VLESS RESTORE ☘️</b>
━━━━━━━━━━━━━━━━━━━━━━━
<code>User     :</code> <code>$user</code>
<code>Domain   :</code> <code>${domain}</code>
<code>ISP      :</code> <code>$ISP</code>
<code>CITY     :</code> <code>$CITY</code>
<code>IP Limit :</code> <code>$iplim IP</code>
<code>Quota Limit :</code> <code>$Quota GB</code>
<code>Expired  :</code> <code>$newdate</code>
━━━━━━━━━━━━━━━━━━━━━━━
<i>Succes Restore This Account...</i>
"
    curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
    cd
    if [ ! -e /etc/tele ]; then
        echo -ne
    else
        echo "$TEXT" > /etc/notiftele
        bash /etc/tele
    fi
    clear
    echo
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    judul " Vless Account Restore Successfully"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo " Client Name : $user"
    echo " Expired     : $newdate"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo
    bottelegram > /dev/null 2>&1 &
    kembali
    exec $0 && exit 0
}

function quota-user(){
    cd
    clear
    if [ ! -e /etc/vless/userQuota ]; then
        echo > /etc/vless/userQuota
    fi
    NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/vless/userQuota")
    if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        judul "      ◈ Unlock Vless Account ◈     "
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo
        tebal "          Tidak ada user!!"
        echo
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        kembali
        exec $0 && exit 0
    fi
    clear
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    judul "      ◈ Unlock Vless Account ◈     "
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    tebal "Please choose the client to Unlock"
    tebal "ketik [0] kembali ke menu"
    tebal "ketik [999] untuk delete semua Akun"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    printf "${W}  %-5s %-15s %s\n" "No" "Name" "Expired"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    grep -E "^### " "/etc/vless/userQuota" | cut -d ' ' -f 2-3 | nl -s ') ' | while read -r line; do
        number=$(echo "$line" | cut -d')' -f 1 | xargs); name=$(echo "$line" | cut -d' ' -f 2); expired=$(echo "$line" | cut -d' ' -f 3-)
        printf "  %-5s %-15s %s\n" "$number" "$name" "$expired"
    done
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
        if [[ ${CLIENT_NUMBER} == '1' ]]; then
            read -rp " Select one client [1]: " CLIENT_NUMBER
        else
            read -rp " Select one client [1-${NUMBER_OF_CLIENTS}] to Unlock: " CLIENT_NUMBER
            if [[ ${CLIENT_NUMBER} == '0' ]]; then
                exec $0 && exit 0
            fi
            if [[ ${CLIENT_NUMBER} == '999' ]]; then
                rm /etc/vless/userQuota
                exec $0 && exit 0
            fi
        fi
    done
    user=$(grep -E "^### " "/etc/vless/userQuota" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
    exp=$(grep -E "^### " "/etc/vless/userQuota" | cut -d ' ' -f 3 | sed -n "${CLIENT_NUMBER}"p)
    uuid=$(grep -E "^### " "/etc/vless/userQuota" | cut -d ' ' -f 4 | sed -n "${CLIENT_NUMBER}"p)
    sed -i '/#vless$/a\#vl '"$user $exp $uuid"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
    sed -i '/#vlessgrpc$/a\#vlg '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
    sed -i "/^### $user $exp $uuid/d" /etc/vless/userQuota
    systemctl restart xray
    TEXT="
━━━━━━━━━━━━━━━━━━━━━━━
<b>☘️ XRAY VLESS UNLOCK ☘️</b>
━━━━━━━━━━━━━━━━━━━━━━━
<code>User    :</code> <code>$user</code>
<code>Domain  :</code> <code>${domain}</code>
<code>ISP     :</code> <code>$ISP</code>
<code>CITY    :</code> <code>$CITY</code>
<code>Expired :</code> <code>$exp</code>
━━━━━━━━━━━━━━━━━━━━━━━
<i>Succes Unlock This Account...</i>
"
    curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
    cd
    if [ ! -e /etc/tele ]; then
        echo -ne
    else
        echo "$TEXT" > /etc/notiftele
        bash /etc/tele
    fi
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo " Vless Account Unlock Successfully"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo " Client Name : $user"
    echo " Status      : Unlocked"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo
    bottelegram > /dev/null 2>&1 &
    kembali
    exec $0 && exit 0
}

clear
author=$(cat /etc/profil)
echo -e " ${U}╭════════════════════════════════════════════════════╮${N}"
echo -e " ${U}│${N}${O}                ${W}● VLESS PANEL MENU ●                ${N}${U}│${N}"
echo -e " ${U}╰════════════════════════════════════════════════════╯${N}"
echo -e " ${U}╭════════════════════════════════════════════════════╮${N}"
echo -e " ${U}│ ${N}${W}[${U}01${W}]${N} ${U}● ${W}ADD AKUN${N}          ${W}[${U}06${W}]${N} ${U}● ${W}CEK USER CONFIG${N}    ${U}│${N}"
echo -e " ${U}│ ${N}${W}[${U}02${W}]${N} ${U}● ${W}TRIAL AKUN${N}        ${W}[${U}07${W}]${N} ${U}● ${W}CHANGE USER LIMIT${N}  ${U}│${N}"
echo -e " ${U}│ ${N}${W}[${U}03${W}]${N} ${U}● ${W}RENEW AKUN${N}        ${W}[${U}08${W}]${N} ${U}● ${W}SETTING LOCK LOGIN${N} ${U}│${N}"
echo -e " ${U}│ ${N}${W}[${U}04${W}]${N} ${U}● ${W}DELETE AKUN${N}       ${W}[${U}09${W}]${N} ${U}● ${W}UNLOCK USER LOGIN${N}  ${U}│${N}"
echo -e " ${U}│ ${N}${W}[${U}05${W}]${N} ${U}● ${W}CEK USER LOGIN${N}    ${W}[${U}10${W}]${N} ${U}● ${W}UNLOCK USER QUOTA ${N} ${U}│${N}"
echo -e " ${U}│ ${N}${W}[${U}00${W}]${N} ${U}● ${W}GO BACK${N}           ${W}[${U}11${W}]${N} ${U}● ${W}RESTORE AKUN   ${N}    ${U}│${N}"
echo -e " ${U}╰════════════════════════════════════════════════════╯${N}"
echo -e " ${U}╭══════════════════════${W} ● BY${N} ● ${U}══════════════════════╮${N}"
cetak_judul
echo -e " ${U}╰════════════════════════════════════════════════════╯${N}"
echo -ne "  ${W}Select menu ${U}: ${W}"; read opt
case $opt in
	1) clear ; add-vless ; exit 0 ;;
	2) clear ; trial-vless ; exit 0 ;;
	3) clear ; renew-vless ; exit 0 ;;
	4) clear ; del-vless ; exit 0 ;;
	5) clear ; cek-vless ; exit 0 ;;
	6) clear ; list-vless ; exit 0 ;;
	7) clear ; limit-vless ; exit 0 ;;
	8) clear ; login-vless ; exit 0 ;;
	9) clear ; lock-vless ; exit 0 ;;
	10) clear ; quota-user ; exit 0 ;;
	11) clear ; res-user ; exit 0 ;;
	0) clear ; exec menu ; exit 0 ;;
	x) exit 0 ;;
	*) echo -e "  ${R}Input is not valid!${N}" ; sleep 1 ; exec $0 ; exit 0 ;;
esac
exit 0
