#!/bin/bash
exit_clean() { echo " Dihentikan"; exit 0; }
trap exit_clean SIGINT
engkok=$0
REPOKU="https://github.com/optimus-glitch/newsc/main"
REPOSC="https://github.com/optimus-glitch/newsc/main"
biji=`date +"%Y-%m-%d" -d "$dateFromServer"`
colornow=$(cat /etc/alawivpn/theme/color.conf)
NC="\e[0m"
R='\e[1;91m'
COLOR1="$(cat /etc/alawivpn/theme/$colornow | grep -w "TEXT" | cut -d: -f2|sed 's/ //g')"
COLBG1="$(cat /etc/alawivpn/theme/$colornow | grep -w "BG" | cut -d: -f2|sed 's/ //g')"
WH='\033[1;37m'
U=$COLOR1
O=$COLBG1
W=$WH
N=$NC
ipsaya=$(wget -qO- ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="${REPOKU}/registrasi.txt"
checking_sc() {
    useexp=$(curl -sS "$data_ip" | grep "$ipsaya" | awk '{print $3}')
    [[ "$date_list" > "$useexp" ]] && { systemctl stop nginx kyt xray ws-stunnel; dilarang; exit 1; }
}
checking_sc
author=$(cat /etc/profil)
lebar=54
judul="$author"
penyamaan() {
    lebar_judul=${#judul}
    peluasan=$(( (lebar - lebar_judul) /2 -1 ))
    padding=""
    for ((i=0; i<peluasan; i++)); do
        padding+=" "
    done
}
cetak_judul(){
    penyamaan
    if (( lebar_judul % 2 == 1 )); then
        printf " $U%s$N%s$W%s$N%s$U%s$N\n" "│" "$padding" "$judul" "$padding " "│"
    else
        printf " $U%s$N%s$W%s$N%s$U%s$N\n" "│" "$padding" "$judul" "$padding" "│"
    fi
}

# FUNGSIKU
garis(){ echo -e " $U$*$N"; }
judul(){ echo -e " $O$*$N"; }
tebal(){ echo -e " $W$*$N"; }
kembali(){ read -n 1 -s -r -p " Press any key to back on menu "; }

clear
cd
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
TIMES="10"
CHATID=$(cat /etc/per/id)
KEY=$(cat /etc/per/token)
URL="https://api.telegram.org/bot$KEY/sendMessage"
domain=`cat /etc/xray/domain`
CHATID2=$(cat /etc/perlogin/id)
KEY2=$(cat /etc/perlogin/token)
URL2="https://api.telegram.org/bot$KEY2/sendMessage"
cd
if [ ! -e /etc/vmess/akun ]; then
    mkdir -p /etc/vmess/akun
fi
function add-vmess(){
    clear
    until [[ $user =~ ^[a-zA-Z0-9_.-]+$ && ${CLIENT_EXISTS} == '0' ]]; do
        echo -e " ${U}╭═════════════════════════════════════════════════╮${N}"
        echo -e " ${U}│${N}${O}             ${W}● Add Vmess Account ●               ${N}${U}│ ${N}"
        echo -e " ${U}╰═════════════════════════════════════════════════╯${N}"
        echo -e ""
        read -rp "  Input username: " -e user
        CLIENT_EXISTS=$(grep -w $user /etc/xray/config.json | wc -l)
        if [[ ${CLIENT_EXISTS} == '1' ]]; then
            clear
            echo -e " ${U}╭═════════════════════════════════════════════════╮${N}"
            echo -e " ${U}│ ${N} ${O}            ${W}● Add Vmess Account ●              ${N}${U}│ ${N}"
            echo -e " ${U}╰═════════════════════════════════════════════════╯${N}"
            echo -e " ${U}╭═════════════════════════════════════════════════╮${N}"
            echo -e " ${U}│                                                 │"
            echo -e " ${U}│${W} Nama Duplikat Silahkan Buat Nama Lain.          ${U}│"
            echo -e " ${U}│                                                 │"
            echo -e " ${U}╰═════════════════════════════════════════════════╯${N}"
            read -n 1 -s -r -p "  Press any key to back"
            add-vmess
        fi
    done
    uuid=$(cat /proc/sys/kernel/random/uuid)
    until [[ $masaaktif =~ ^[0-9]+$ ]]; do
        read -p "  Expired (days): " masaaktif
    done
    exp=`date -d "$masaaktif days" +"%Y-%m-%d"`
    until [[ $iplim =~ ^[0-9]+$ ]]; do
        read -p "  Limit IP or 0 (unlimited): " iplim
    done
    until [[ $Quota =~ ^[0-9]+$ ]]; do
        read -p "  Limit GB or 0 (Unlimited): " Quota
    done
    if [ ! -e /etc/vmess ]; then
        mkdir -p /etc/vmess
    fi
    if [ ${iplim} = '0' ]; then
        iplim="999999999"
    fi
    if [ ${Quota} = '0' ]; then
        Quota="999999999"
    fi
    c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
    d=$((${c} * 1024 * 1024 * 1024))
    if [[ ${c} != "0" ]]; then
        echo "${d}" >/etc/vmess/${user}
    fi
    echo "${iplim}" >/etc/vmess/${user}IP
    exp=`date -d "$masaaktif days" +"%Y-%m-%d"`
sed -i '/#vmess$/a\#vm '"$user $exp"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' /etc/xray/config.json
sed -i '/#vmessgrpc$/a\#vmg '"$user $exp $uuid"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' /etc/xray/config.json
    asu=`cat<<EOF
{
"v": "2",
"ps": "${user}",
"add": "${domain}",
"port": "443",
"id": "${uuid}",
"aid": "0",
"net": "ws",
"path": "/vmess",
"type": "none",
"host": "${domain}",
"tls": "tls"
}
EOF`
ask=`cat<<EOF
{
"v": "2",
"ps": "${user}",
"add": "${domain}",
"port": "80",
"id": "${uuid}",
"aid": "0",
"net": "ws",
"path": "/vmess",
"type": "none",
"host": "${domain}",
"tls": "none"
}
EOF`
grpc=`cat<<EOF
{
"v": "2",
"ps": "${user}",
"add": "${domain}",
"port": "443",
"id": "${uuid}",
"aid": "0",
"net": "grpc",
"path": "vmess-grpc",
"type": "none",
"host": "${domain}",
"tls": "tls"
}
EOF`
    vmess_base641=$( base64 -w 0 <<< $vmess_json1)
    vmess_base642=$( base64 -w 0 <<< $vmess_json2)
    vmess_base643=$( base64 -w 0 <<< $vmess_json3)
    vmesslink1="vmess://$(echo $asu | base64 -w 0)"
    vmesslink2="vmess://$(echo $ask | base64 -w 0)"
    vmesslink3="vmess://$(echo $grpc | base64 -w 0)"
    VMESS_WS=`cat<<EOF
{
"v": "2",
"ps": "${user}",
"add": "${domain}",
"port": "443",
"id": "${uuid}",
"aid": "0",
"net": "ws",
"path": "/vmess",
"type": "none",
"host": "${domain}",
"tls": "tls"
}
EOF`
VMESS_NON_TLS=`cat<<EOF
{
"v": "2",
"ps": "${user}",
"add": "${domain}",
"port": "80",
"id": "${uuid}",
"aid": "0",
"net": "ws",
"path": "/vmess",
"type": "none",
"host": "${domain}",
"tls": "none"
}
EOF`
VMESS_GRPC=`cat<<EOF
{
"v": "2",
"ps": "${user}",
"add": "${domain}",
"port": "443",
"id": "${uuid}",
"aid": "0",
"net": "grpc",
"path": "/vmess-grpc",
"type": "none",
"host": "${domain}",
"tls": "tls"
}
EOF`
VMESS_OPOK=`cat<<EOF
{
"v": "2",
"ps": "${user}",
"add": "${domain}",
"port": "80",
"id": "${uuid}",
"aid": "0",
"net": "ws",
"path": "http://tsel.me/worryfree",
"type": "none",
"host": "tsel.me",
"tls": "none"
}
EOF`
    cat > /home/vps/public_html/vmess-$user.txt <<-END
-------------------------------------------
Format Vmess WS (CDN)
-------------------------------------------
- name: vmess-$user-WS (CDN)
type: vmess
server: ${domain}
port: 443
uuid: ${uuid}
alterId: 0
cipher: auto
udp: true
tls: true
skip-cert-verify: true
servername: ${domain}
network: ws
ws-opts:
path: /vmess
headers:
Host: ${domain}
-------------------------------------------
Format Vmess WS (CDN) Non TLS
-------------------------------------------
- name: vmess-$user-WS (CDN) Non TLS
type: vmess
server: ${domain}
port: 80
uuid: ${uuid}
alterId: 0
cipher: auto
udp: true
tls: false
skip-cert-verify: false
servername: ${domain}
network: ws
ws-opts:
path: /vmess
headers:
Host: ${domain}
-------------------------------------------
Format Vmess gRPC (SNI)
-------------------------------------------
- name: vmess-$user-gRPC (SNI)
server: ${domain}
port: 443
type: vmess
uuid: ${uuid}
alterId: 0
cipher: auto
network: grpc
tls: true
servername: ${domain}
skip-cert-verify: true
grpc-opts:
grpc-service-name: vmess-grpc
-------------------------------------------
Format Vmess WS (CDN) Non TLS Opok TSEL
-------------------------------------------
- name: vmess-$user-WS (CDN) Non TLS
type: vmess
server: ${domain}
port: 80
uuid: ${uuid}
alterId: 0
cipher: auto
udp: true
tls: false
skip-cert-verify: true
servername: comunity.instagram.com
network: ws
ws-opts:
path: : http://tsel.me/worryfree
headers:
Host: ${domain}
-------------------------------------------
Link Vmess Account
-------------------------------------------
Link TLS : vmess://$(echo $VMESS_WS | base64 -w 0)
-------------------------------------------
Link NTLS : vmess://$(echo $VMESS_NON_TLS | base64 -w 0)
-------------------------------------------
Link gRPC : vmess://$(echo $VMESS_GRPC | base64 -w 0)
-------------------------------------------
Link Opok : vmess://$(echo $VMESS_OPOK | base64 -w 0)
-------------------------------------------
END
    if [ ${Quota} = '999999999' ]; then
        TEXT="
════════════════════
<b>    ☘️ Premium Vmess Account ☘️</b>
════════════════════
<code>User         :</code> <code>${user}</code>
<code>Domain       :</code> <code>${domain}</code>
<code>Login Limit  :</code> <code>${iplim} IP</code>
<code>Quota Limit  :</code> <code>${Quota} GB</code>
<code>ISP          :</code> <code>${ISP}</code>
<code>CITY         :</code> <code>${CITY}</code>
<code>Port TLS     :</code> <code>443</code>
<code>Port NTLS    :</code> <code>80, 8080</code>
<code>Port GRPC    :</code> <code>443</code>
<code>UUID         :</code> <code>${uuid}</code>
<code>AlterId      :</code> <code>0</code>
<code>Security     :</code> <code>auto</code>
<code>Network      :</code> <code>WS or gRPC</code>
<code>Path         :</code> <code>/vmess</code>
<code>Path Support :</code> <code>https://bug.com/vmess</code>
<code>ServiceName  :</code> <code>vmess-grpc</code>
════════════════════
<b>Link TLS     :</b>
<code>${vmesslink1}</code>
════════════════════
<b>Link NTLS    :</b>
<code>${vmesslink2}</code>
════════════════════
<b>Link GRPC    :</b>
<code>${vmesslink3}</code>
════════════════════
<b>Format OpenClash :</b>
http://$domain:89/vmess-$user.txt
════════════════════
<code>Expired Date    :</code> <b>$exp</b>
════════════════════
<b>$author</b>
════════════════════
"
    else
        TEXT="
━━━━━━━━━━━━━━━━━━━━
<b>    ☘️ Premium Vmess Account ☘️</b>
━━━━━━━━━━━━━━━━━━━━
<code>User         :</code> <code>${user}</code>
<code>Domain       :</code> <code>${domain}</code>
<code>Login Limit  :</code> <code>${iplim} IP</code>
<code>Quota Limit  :</code> <code>${Quota} GB</code>
<code>ISP          :</code> <code>${ISP}</code>
<code>CITY         :</code> <code>${CITY}</code>
<code>Port TLS     :</code> <code>443</code>
<code>Port NTLS    :</code> <code>80, 8080</code>
<code>Port GRPC    :</code> <code>443</code>
<code>UUID         :</code> <code>${uuid}</code>
<code>AlterId      :</code> <code>0</code>
<code>Security     :</code> <code>auto</code>
<code>Network      :</code> <code>WS or gRPC</code>
<code>Path         :</code> <code>/vmess</code>
<code>Path Support :</code> <code>https://bug.com/vmess</code>
<code>ServiceName  :</code> <code>vmess-grpc</code>
━━━━━━━━━━━━━━━━━━━━
<b>Link TLS     :</b>
<code>${vmesslink1}</code>
━━━━━━━━━━━━━━━━━━━━
<b>Link NTLS    :</b>
<code>${vmesslink2}</code>
━━━━━━━━━━━━━━━━━━━━
<b>Link GRPC    :</b>
<code>${vmesslink3}</code>
━━━━━━━━━━━━━━━━━━━━
<b>Format OpenClash :</b>
http://${domain}:89/vmess-${user}.txt
━━━━━━━━━━━━━━━━━━━━
<code>Expired :</code> <b>${exp}</b>
━━━━━━━━━━━━━━━━━━━━
<b>${author}</b>
━━━━━━━━━━━━━━━━━━━━

"
    fi
    curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
    cd
    if [ ! -e /etc/tele ]; then
        echo -ne
    else
        echo "$TEXT" > /etc/notiftele
        bash /etc/tele
    fi
    user2=$(echo "$user" | cut -c 1-3)
    TIME2=$(date +'%d-%m-%Y %H:%M:%S')
    TEXT2="
━━━━━━━━━━━━━━━━━━━━━━━
<b>     ☘ VMESS PREMIUM SOLD ☘</b>
━━━━━━━━━━━━━━━━━━━━━━━
<code>Order  :</code> <code>VMESS Premium</code>
<code>User   :</code> <code>${user2}⬤⬤⬤</code>
<code>Domain :</code> <code>${domain}</code>
<code>ISP    :</code> <code>${ISP}</code>
<code>CITY   :</code> <code>$CITY</code>
<code>Date   :</code> <code>${TIME2} WIB</code>
<code>Limit  :</code> <code>${iplim} IP</code>
<code>Aktif  :</code> <code>$masaaktif Hari</code>
━━━━━━━━━━━━━━━━━━━━━━━
<i>Succes create this vmess account..</i>"
    curl -s --max-time $TIMES -d "chat_id=$CHATID2&disable_web_page_preview=1&text=$TEXT2&parse_mode=html" $URL2 >/dev/null
    clear
    echo -e "━━━━━━━━━━━━━━━━━━━━━━━ " | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "● Premium Vmess Account ●   " | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "━━━━━━━━━━━━━━━━━━━━━━━ " | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "User          : ${user}" | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "ISP           : $ISP" | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "City          : $CITY" | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "Domain        : ${domain}" | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "Login Limit   : ${iplim} IP" | tee -a /etc/vmess/akun/log-create-${user}.log
    if [ ${Quota} = '999999999' ]; then
        echo -ne
    else
        echo -e "Quota Limit   : ${Quota} GB" | tee -a /etc/vmess/akun/log-create-${user}.log
    fi
    echo -e "Port TLS      : 443" | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "Port NTLS     : 80,8080" | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "Port gRPC     : 443" | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "UUID          : ${uuid}" | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "alterId       : 0" | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "Security      : auto" | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "Network       : ws" | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "Path          : /vmess" | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "Path Support  : http://bug/vmess" | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "ServiceName   : vmess-grpc" | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "━━━━━━━━━━━━━━━━━━━━━━━ " | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "Link Websocket TLS :" | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "${vmesslink1}"  | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "━━━━━━━━━━━━━━━━━━━━━━━ " | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "Link Websocket NTLS :" | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "${vmesslink2}"  | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "━━━━━━━━━━━━━━━━━━━━━━━ " | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "Link Websocket gRPC : " | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "${vmesslink3}"  | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "━━━━━━━━━━━━━━━━━━━━━━━ " | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "Format Openclash :" | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "http://$domain:89/vmess-$user.txt" | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "━━━━━━━━━━━━━━━━━━━━━━━ " | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "Expired Akun    : $exp" | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "━━━━━━━━━━━━━━━━━━━━━━━ " | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "      $author     " | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "━━━━━━━━━━━━━━━━━━━━━━━ " | tee -a /etc/vmess/akun/log-create-${user}.log
    echo | tee -a /etc/vmess/akun/log-create-${user}.log
    systemctl restart xray > /dev/null 2>&1
    bottelegram > /dev/null 2>&1 &
    kembali
    exec $0 && exit 0
}
function trial-vmess(){
    clear
    cd
    echo -e " ${U}╭═════════════════════════════════════════════════╮${N}"
    echo -e " ${U}│${N}${O}            ● Trial Vmess Account ●              ${N}${U}│ ${N}"
    echo -e " ${U}╰═════════════════════════════════════════════════╯${N}"
    echo -e ""
    until [[ $timer =~ ^[0-9]+$ ]]; do
        read -p "  Input times (Minutes): " timer
    done
    user=Trial-`</dev/urandom tr -dc X-Z0-9 | head -c4`
    iplim=1
    Quota=1
    uuid=$(cat /proc/sys/kernel/random/uuid)
    masaaktif=0
    if [ ! -e /etc/vmess ]; then
        mkdir -p /etc/vmess
    fi
    c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
    d=$((${c} * 1024 * 1024 * 1024))
    if [[ ${c} != "0" ]]; then
        echo "${d}" >/etc/vmess/${user}
    fi
    echo "${iplim}" > /etc/vmess/${user}IP
    ecp=$(date -d "+$timer minutes" +"%Y-%m-%d %H:%M:%S")
    exp=$(echo $ecp | awk '{print $1}')
    touch /etc/xray/trialvmess
    echo -e "### $user $ecp" >> /etc/xray/trialvmess
sed -i '/#vmess$/a\#vm '"$user $exp"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' /etc/xray/config.json
sed -i '/#vmessgrpc$/a\#vmg '"$user $exp $uuid"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' /etc/xray/config.json
asu=`cat<<EOF
{
"v": "2",
"ps": "${user}",
"add": "${domain}",
"port": "443",
"id": "${uuid}",
"aid": "0",
"net": "ws",
"path": "/vmess",
"type": "none",
"host": "${domain}",
"tls": "tls"
}
EOF`
ask=`cat<<EOF
{
"v": "2",
"ps": "${user}",
"add": "${domain}",
"port": "80",
"id": "${uuid}",
"aid": "0",
"net": "ws",
"path": "/vmess",
"type": "none",
"host": "${domain}",
"tls": "none"
}
EOF`
grpc=`cat<<EOF
{
"v": "2",
"ps": "${user}",
"add": "${domain}",
"port": "443",
"id": "${uuid}",
"aid": "0",
"net": "grpc",
"path": "vmess-grpc",
"type": "none",
"host": "${domain}",
"tls": "tls"
}
EOF`
vmess_base641=$( base64 -w 0 <<< $vmess_json1)
vmess_base642=$( base64 -w 0 <<< $vmess_json2)
vmess_base643=$( base64 -w 0 <<< $vmess_json3)
vmesslink1="vmess://$(echo $asu | base64 -w 0)"
vmesslink2="vmess://$(echo $ask | base64 -w 0)"
vmesslink3="vmess://$(echo $grpc | base64 -w 0)"
VMESS_WS=`cat<<EOF
{
"v": "2",
"ps": "${user}",
"add": "${domain}",
"port": "443",
"id": "${uuid}",
"aid": "0",
"net": "ws",
"path": "/vmess",
"type": "none",
"host": "${domain}",
"tls": "tls"
}
EOF`
VMESS_NON_TLS=`cat<<EOF
{
"v": "2",
"ps": "${user}",
"add": "${domain}",
"port": "80",
"id": "${uuid}",
"aid": "0",
"net": "ws",
"path": "/vmess",
"type": "none",
"host": "${domain}",
"tls": "none"
}
EOF`
VMESS_GRPC=`cat<<EOF
{
"v": "2",
"ps": "${user}",
"add": "${domain}",
"port": "443",
"id": "${uuid}",
"aid": "0",
"net": "grpc",
"path": "/vmess-grpc",
"type": "none",
"host": "${domain}",
"tls": "tls"
}
EOF`
VMESS_OPOK=`cat<<EOF
{
"v": "2",
"ps": "${user}",
"add": "${domain}",
"port": "80",
"id": "${uuid}",
"aid": "0",
"net": "ws",
"path": "http://tsel.me/worryfree",
"type": "none",
"host": "tsel.me",
"tls": "none"
}
EOF`
cat > /home/vps/public_html/vmess-$user.txt <<-END
-------------------------------------------
Format Vmess WS (CDN)
-------------------------------------------
- name: vmess-$user-WS (CDN)
type: vmess
server: ${domain}
port: 443
uuid: ${uuid}
alterId: 0
cipher: auto
udp: true
tls: true
skip-cert-verify: true
servername: ${domain}
network: ws
ws-opts:
path: /vmess
headers:
Host: ${domain}
-------------------------------------------
Format Vmess WS (CDN) Non TLS
-------------------------------------------
- name: vmess-$user-WS (CDN) Non TLS
type: vmess
server: ${domain}
port: 80
uuid: ${uuid}
alterId: 0
cipher: auto
udp: true
tls: false
skip-cert-verify: false
servername: ${domain}
network: ws
ws-opts:
path: /vmess
headers:
Host: ${domain}
-------------------------------------------
Format Vmess gRPC (SNI)
-------------------------------------------
- name: vmess-$user-gRPC (SNI)
server: ${domain}
port: 443
type: vmess
uuid: ${uuid}
alterId: 0
cipher: auto
network: grpc
tls: true
servername: ${domain}
skip-cert-verify: true
grpc-opts:
grpc-service-name: vmess-grpc
-------------------------------------------
Format Vmess WS (CDN) Non TLS Opok TSEL
-------------------------------------------
- name: vmess-$user-WS (CDN) Non TLS
type: vmess
server: ${domain}
port: 80
uuid: ${uuid}
alterId: 0
cipher: auto
udp: true
tls: false
skip-cert-verify: true
servername: comunity.instagram.com
network: ws
ws-opts:
path: http://tsel.me/worryfree
headers:
Host: ${domain}
-------------------------------------------
Link Vmess Account
-------------------------------------------
Link TLS : vmess://$(echo $VMESS_WS | base64 -w 0)
-------------------------------------------
Link NTLS : vmess://$(echo $VMESS_NON_TLS | base64 -w 0)
-------------------------------------------
Link gRPC : vmess://$(echo $VMESS_GRPC | base64 -w 0)
-------------------------------------------
Link Opok : vmess://$(echo $VMESS_OPOK | base64 -w 0)
-------------------------------------------
END
TEXT="
━━━━━━━━━━━━━━━━━━━━━━━
<b>☘️ Trial Premium Vmess Account ☘️</b>
━━━━━━━━━━━━━━━━━━━━━━━
<code>User         :</code> <code>${user}</code>
<code>Domain       :</code> <code>${domain}</code>
<code>Login Limit  :</code> <code>${iplim} IP</code>
<code>ISP          :</code> <code>${ISP}</code>
<code>CITY         :</code> <code>${CITY}</code>
<code>Port TLS     :</code> <code>443</code>
<code>Port NTLS    :</code> <code>80, 8080</code>
<code>Port GRPC    :</code> <code>443</code>
<code>UUID         :</code> <code>${uuid}</code>
<code>AlterId      :</code> <code>0</code>
<code>Security     :</code> <code>auto</code>
<code>Network      :</code> <code>WS or gRPC</code>
<code>Path         :</code> <code>/vmess</code>
<code>Path Support :</code> <code>https://bug.com/vmess</code>
<code>ServiceName  :</code> <code>vmess-grpc</code>
━━━━━━━━━━━━━━━━━━━━━━━
<b>Link TLS     :</b>
<code>${vmesslink1}</code>
━━━━━━━━━━━━━━━━━━━━━━━
<b>Link NTLS    :</b>
<code>${vmesslink2}</code>
━━━━━━━━━━━━━━━━━━━━━━━
<b>Link GRPC    :</b>
<code>${vmesslink3}</code>
━━━━━━━━━━━━━━━━━━━━━━━
<b>Format OpenClash :</b>
http://${domain}:89/vmess-${user}.txt
━━━━━━━━━━━━━━━━━━━━━━━
<code>Expired :</code> <b>${ecp}</b>
━━━━━━━━━━━━━━━━━━━━━━━
<b>${author}</b>
━━━━━━━━━━━━━━━━━━━━━━━

"
    curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
    cd
    if [ ! -e /etc/tele ]; then
        echo -ne
    else
        echo "$TEXT" > /etc/notiftele
        bash /etc/tele
    fi
    clear
    echo -e "━━━━━━━━━━━━━━━━━━━━━━━ " | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "● Trial Premium Vmess Account ● " | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "━━━━━━━━━━━━━━━━━━━━━━━ " | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "User          : ${user}" | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "ISP           : $ISP" | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "City          : $CITY" | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "Domain        : ${domain}" | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "Login Limit   : ${iplim} IP" | tee -a /etc/log-create-.log
    echo -e "Port TLS      : 443" | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "Port NTLS     : 80,8080" | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "Port gRPC     : 443" | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "UUID          : ${uuid}" | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "alterId       : 0" | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "Security      : auto" | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "Network       : ws" | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "Path          : /vmess" | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "Path Support  : http://bug/vmess" | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "ServiceName   : vmess-grpc" | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "━━━━━━━━━━━━━━━━━━━━━━━ " | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "Link Websocket TLS      :" | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "${vmesslink1}"| tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "━━━━━━━━━━━━━━━━━━━━━━━ " | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "Link Websocket NTLS : " | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "${vmesslink2}"| tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "━━━━━━━━━━━━━━━━━━━━━━━ " | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "Link Websocket gRPC     : " | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "${vmesslink3}"| tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "━━━━━━━━━━━━━━━━━━━━━━━ " | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "Format Openclash :" | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "http://$domain:89/vmess-$user.txt" | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "━━━━━━━━━━━━━━━━━━━━━━━ " | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "Expired Date     : $ecp" | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "━━━━━━━━━━━━━━━━━━━━━━━ " | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "    $author     " | tee -a /etc/vmess/akun/log-create-${user}.log
    echo -e "━━━━━━━━━━━━━━━━━━━━━━━ " | tee -a /etc/vmess/akun/log-create-${user}.log
    echo | tee -a /etc/vmess/akun/log-create-${user}.log
    systemctl restart xray > /dev/null 2>&1
    kembali
    exec $0 && exit 0
}
function renew-vmess(){
    clear
    NUMBER_OF_CLIENTS=$(grep -c -E "^#vmg " "/etc/xray/config.json")
    if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
        clear
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        judul "      ◈ Renew Vmess Account ◈      "
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo
        tebal "          Tidak ada user!!"
        echo
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo
        kembali
        exec $0 && exit 0
    fi
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    judul "      ◈ Renew Vmess Account ◈      "
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    tebal "Please choose the client to renew"
    tebal "ketik [0] kembali ke menu"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    printf "${W}  %-5s %-15s %s\n" "No" "Name" "Expired"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    grep -E "^#vmg " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | nl -s ') ' | while read -r line; do
        number=$(echo "$line" | cut -d')' -f 1 | xargs); name=$(echo "$line" | cut -d' ' -f 2); expired=$(echo "$line" | cut -d' ' -f 3-)
        printf "  %-5s %-15s %s\n" "$number" "$name" "$expired"
    done
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
        if [[ ${CLIENT_NUMBER} == '1' ]]; then
            read -rp " Select one client [1]: " CLIENT_NUMBER
        else
            read -rp " Select one client [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER
            if [[ ${CLIENT_NUMBER} == '0' ]]; then
                exec $0 && exit 0
            fi
        fi
    done
    read -p " Days extend: " masaaktif
    user=$(grep -E "^#vmg " "/etc/xray/config.json" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
    exp=$(grep -E "^#vmg " "/etc/xray/config.json" | cut -d ' ' -f 3 | sed -n "${CLIENT_NUMBER}"p)
    now=$(date +%Y-%m-%d)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    exp2=$(( (d1 - d2) / 86400 ))
    exp3=$(($exp2 + $masaaktif))
    exp4=`date -d "$exp3 days" +"%Y-%m-%d"`
    sed -i "s/#vm $user $exp/#vm $user $exp4/g" /etc/xray/config.json
    sed -i "s/#vmg $user $exp/#vmg $user $exp4/g" /etc/xray/config.json
    clear
TEXT="
━━━━━━━━━━━━━━━━━━━━━━━
<b>☘️ XRAY VMESS RENEW ☘️</b>
━━━━━━━━━━━━━━━━━━━━━━━
<code>User    :</code> <code>$user</code>
<code>Domain  :</code> <code>${domain}</code>
<code>ISP     :</code> <code>$ISP</code>
<code>CITY    :</code> <code>$CITY</code>
<code>Expired :</code> <code>$exp4</code>
━━━━━━━━━━━━━━━━━━━━━━━
<i>Succes Renew This Account..</i>
"
    curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
    cd
    if [ ! -e /etc/tele ]; then
        echo -ne
    else
        echo "$TEXT" > /etc/notiftele
        bash /etc/tele
    fi
    user2=$(echo "$user" | cut -c 1-3)
    TIME2=$(date +'%Y-%m-%d %H:%M:%S')
TEXT2="
━━━━━━━━━━━━━━━━━━━━━━━
<b>     ☘ VMESS PREMIUM SOLD ☘</b>
━━━━━━━━━━━━━━━━━━━━━━━
<code>Order  :</code> <code>VMESS Premium</code>
<code>User   :</code> <code>${user2}⬤⬤⬤</code>
<code>Domain :</code> <code>${domain}</code>
<code>ISP    :</code> <code>$ISP</code>
<code>CITY   :</code> <code>$CITY</code>
<code>Date   :</code> <code>${TIME2} WIB</code>
<code>Aktif  :</code> <code>$masaaktif Hari</code>
━━━━━━━━━━━━━━━━━━━━━━━
<i>Succes Renew This Account...</i>
"
    curl -s --max-time $TIMES -d "chat_id=$CHATID2&disable_web_page_preview=1&text=$TEXT2&parse_mode=html" $URL2 >/dev/null
    systemctl restart xray > /dev/null 2>&1
    clear
    echo
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    judul "VMESS Account Was Successfully Renewed"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo
    tebal "Client Name : $user"
    tebal "Expired On  : $exp4"
    echo
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo
    bottelegram > /dev/null 2>&1 &
    kembali
    exec $0 && exit 0
}
function limit-vmess(){
    clear
    NUMBER_OF_CLIENTS=$(grep -c -E "^#vmg " "/etc/xray/config.json")
    if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
        clear
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        judul "      ◈ Limit Vmess Account ◈      "
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo
        tebal "          Tidak ada user!!"
        echo
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo
        kembali
        exec $0 && exit 0
    fi
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    judul "      ◈ Limit Vmess Account ◈      "
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    tebal "Please choose the client to change ip"
    tebal "ketik [0] kembali ke menu"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    printf "${W}  %-5s %-15s %s\n" "No" "Name" "Expired"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    grep -E "^#vmg " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | nl -s ') ' | while read -r line; do
        number=$(echo "$line" | cut -d')' -f 1 | xargs); name=$(echo "$line" | cut -d' ' -f 2); expired=$(echo "$line" | cut -d' ' -f 3-)
        printf "  %-5s %-15s %s\n" "$number" "$name" "$expired"
    done
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
        if [[ ${CLIENT_NUMBER} == '1' ]]; then
            read -rp " Select one client [1]: " CLIENT_NUMBER
        else
            read -rp " Select one client [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER
            if [[ ${CLIENT_NUMBER} == '0' ]]; then
                exec $0 && exit 0
            fi
        fi
    done
    clear
    until [[ $iplim =~ ^[0-9]+$ ]]; do
        read -p " Limit User (IP) or 0 Unlimited: " iplim
    done
    until [[ $Quota =~ ^[0-9]+$ ]]; do
        read -p "Limit User (GB) or 0 Unlimited: " Quota
    done
    if [ ! -e /etc/vmess ]; then
        mkdir -p /etc/vmess
    fi
    if [ ${iplim} = '0' ]; then
        iplim="999999999"
    fi
    if [ ${Quota} = '0' ]; then
        Quota="999999999"
    fi
    user=$(grep -E "^#vmg " "/etc/xray/config.json" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
    echo "${iplim}" >/etc/vmess/${user}IP
    c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
    d=$((${c} * 1024 * 1024 * 1024))
    if [[ ${c} != "0" ]]; then
        echo "${d}" >/etc/vmess/${user}
    fi
TEXT="
━━━━━━━━━━━━━━━━━━━━━━━
<b>☘️ XRAY VMESS IP LIMIT ☘️</b>
━━━━━━━━━━━━━━━━━━━━━━━
<code>User    :</code> <code>$user</code>
<code>Domain  :</code> <code>${domain}</code>
<code>ISP     :</code> <code>$ISP</code>
<code>CITY    :</code> <code>$CITY</code>
<code>New Limit IP :</code> <code>$iplim IP</code>
<code>New Limit Quota :</code> <code>$Quota GB</code>
━━━━━━━━━━━━━━━━━━━━━━━
<i>Succes Change Limit This Account...</i>
"
    curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
    cd
    if [ ! -e /etc/tele ]; then
        echo -ne
    else
        echo "$TEXT" > /etc/notiftele
        bash /etc/tele
    fi
    clear
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    judul "   Successfully Change Limit IP    "
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo
    tebal "Client Name : $user"
    tebal "Limit IP    : $iplim IP"
    tebal "Limit Quota : $Quota GB"
    echo
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo
    bottelegram > /dev/null 2>&1 &
    kembali
    exec $0 && exit 0
}

function del-vmess(){
    clear
    NUMBER_OF_CLIENTS=$(grep -c -E "^#vmg " "/etc/xray/config.json")
    if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        judul "      ◈ Delete Vmess Account ◈     "
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo
        tebal "          Tidak ada user!!"
        echo
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        kembali
        exec $0 && exit 0
    fi
    clear
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    judul "      ◈ Delete Vmess Account ◈     "
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    tebal "Please choose the client to remove"
    tebal "ketik [0] kembali ke menu"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    printf "${W}  %-5s %-15s %s\n" "No" "Name" "Expired"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    grep -E "^#vmg " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | nl -s ') ' | while read -r line; do
        number=$(echo "$line" | cut -d')' -f 1 | xargs); name=$(echo "$line" | cut -d' ' -f 2); expired=$(echo "$line" | cut -d' ' -f 3-)
        printf "  %-5s %-15s %s\n" "$number" "$name" "$expired"
    done
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
        if [[ ${NUMBER_OF_CLIENTS} == '1' ]]; then
            read -rp " Select one client [1]: " CLIENT_NUMBER
        else
            read -rp " Select one client [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER
            if [[ ${CLIENT_NUMBER} == '0' ]]; then
                exec $0 && exit 0
            fi
        fi
    done
    user=$(grep -E "^#vmg " "/etc/xray/config.json" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
    exp=$(grep -E "^#vmg " "/etc/xray/config.json" | cut -d ' ' -f 3 | sed -n "${CLIENT_NUMBER}"p)
    uuid=$(grep -E "^#vmg " "/etc/xray/config.json" | cut -d ' ' -f 4 | sed -n "${CLIENT_NUMBER}"p)
    if [ ! -e /etc/vmess/akundelete ]; then
        echo > /etc/vmess/akundelete
    fi
    clear
    echo "### $user $exp $uuid" >> /etc/vmess/akundelete
    sed -i "/^#vmg $user $exp/,/^},{/d" /etc/xray/config.json
    sed -i "/^#vm $user $exp/,/^},{/d" /etc/xray/config.json
    rm /etc/vmess/${user}IP
    clear
    rm /home/vps/public_html/vmess-$user.txt >/dev/null 2>&1
    rm /etc/vmess/${user}IP >/dev/null 2>&1
    rm /etc/vmess/${user}login >/dev/null 2>&1
    systemctl restart xray > /dev/null 2>&1
    clear
TEXT="
━━━━━━━━━━━━━━━━━━━━━━━
<b>☘️ XRAY VMESS DELETE ☘️</b>
━━━━━━━━━━━━━━━━━━━━━━━
<code>User    :</code> <code>$user</code>
<code>Domain  :</code> <code>${domain}</code>
<code>ISP     :</code> <code>$ISP</code>
<code>CITY    :</code> <code>$CITY</code>
<code>Expired :</code> <code>$exp</code>
━━━━━━━━━━━━━━━━━━━━━━━
<i>Succes Delete This Account...</i>
"
    curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
    cd
    if [ ! -e /etc/tele ]; then
        echo -ne
    else
        echo "$TEXT" > /etc/notiftele
        bash /etc/tele
    fi
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    judul "Vmess Account Deleted Successfully "
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    tebal "Client Name : $user"
    tebal "Expired On  : $exp"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo
    kembali
    exec $0 && exit 0
}

tim2sec() {
    mult=1
    arg="$1"
    inu=0
    while [ ${#arg} -gt 0 ]; do
        prev="${arg%:*}"
        if [ "$prev" = "$arg" ]; then
            curr="${arg#0}"
            prev=""
        else
            curr="${arg##*:}"
            curr="${curr#0}"
        fi
        curr="${curr%.*}"
        inu=$((inu + curr * mult))
        mult=$((mult * 60))
        arg="$prev"
    done
    echo "$inu"
}
function convert() {
    local -i bytes=$1
    if [[ $bytes -lt 1024 ]]; then
        echo "${bytes} B"
    elif [[ $bytes -lt 1048576 ]]; then
        echo "$(awk "BEGIN {printf \"%.2f\", $bytes/1024}" | sed 's/\.00$//' | sed 's/\.\([0-9]\)0$/.\1/') KB"
    elif [[ $bytes -lt 1073741824 ]]; then
        echo "$(awk "BEGIN {printf \"%.2f\", $bytes/1048576}" | sed 's/\.00$//' | sed 's/\.\([0-9]\)0$/.\1/') MB"
    else
        echo "$(awk "BEGIN {printf \"%.2f\", $bytes/1073741824}" | sed 's/\.00$//' | sed 's/\.\([0-9]\)0$/.\1/') GB"
    fi
}

function cek-vmess(){
    clear
    xrayy=$(cat /var/log/xray/access.log | wc -l)
    if [[ xrayy -le 5 ]]; then
        systemctl restart xray
    fi
    xraylimit
    echo -e " ${U}╭═════════════════════════════════════════════════╮${N}"
    echo -e " ${U}│${N}${O}             ${W}● VMESS USER ONLINE ●               ${N}${U}│ ${N}"
    echo -e " ${U}╰═════════════════════════════════════════════════╯${N}"
    echo -e " ${U}╭═════════════════════════════════════════════════╮${N}"
    vm=($(cat /etc/xray/config.json | grep "^#vmg" | awk '{print $2}' | sort -u))
    echo -n >/tmp/vm
    for db1 in ${vm[@]}; do
        logvm=$(cat /var/log/xray/access.log | grep -w "email: ${db1}" | tail -n 100)
        while read a; do
            if [[ -n ${a} ]]; then
                set -- ${a}
                ina="${7}"
                inu="${2}"
                anu="${3}"
                enu=$(echo "${anu}" | sed 's/tcp://g' | sed '/^$/d' | cut -d. -f1,2,3)
                now=$(tim2sec ${timenow})
                client=$(tim2sec ${inu})
                nowt=$(((${now} - ${client})))
                if [[ ${nowt} -lt 40 ]]; then
                    cat /tmp/vm | grep -w "${ina}" | grep -w "${enu}" >/dev/null
                    if [[ $? -eq 1 ]]; then
                        echo "${ina} ${inu} WIB : ${enu}" >>/tmp/vm
                        splvm=$(cat /tmp/vm)
                    fi
                fi
            fi
        done <<<"${logvm}"
    done
    if [[ ${splvm} != "" ]]; then
        printf " ${U}%-5s${W}%-15s%-12s%-12s%-8s${U}%s\n" "│" "USERNAME" "LOGIN" "USAGE" "LIMIT" "│"
        echo -e " ${U}├═════════════════════════════════════════════════┤${N}"
        for vmuser in ${vm[@]}; do
            vmhas=$(cat /tmp/vm | grep -w "${vmuser}" | wc -l)
            tess=0
            if [[ ${vmhas} -gt $tess ]]; then
                byt=$(cat /etc/limit/vmess/${vmuser})
                gb=$(convert ${byt})
                lim=$(cat /etc/vmess/${vmuser})
                lim2=$(convert ${lim})
                printf " ${U}%-5s\e[0;33m%-17s%-10s%-12s%-8s${U}%s\n" "│" "$vmuser" "$vmhas" "$gb" "$lim2" "│"
            fi
        done
    else
        echo -e " ${U}│                                                 │"
        echo -e " ${U}│${W}             TIDAK ADA USER ONLINE!              ${U}│${N}"
        echo -e " ${U}│                                                 │"
        echo -e " ${U}╰═════════════════════════════════════════════════╯${N}"
        read -n 1 -s -r -p "  Press any key to back on menu"
        exec $0 && exit
    fi
    echo -e " ${U}╰═════════════════════════════════════════════════╯${N}"
    echo -e " ${U}╭═════════════════════════════════════════════════╮${N}"
    echo -e " ${U}│${W}          CODE BY : ALAWI CONFIG-SANTRI          ${U}│${N}"
    echo -e " ${U}╰═════════════════════════════════════════════════╯${N}"
    echo
    read -n 1 -s -r -p "  Press any key to back on menu"
    exec $0 && exit 0
}
function list-vmess(){
    clear
    NUMBER_OF_CLIENTS=$(grep -c -E "^#vmg " "/etc/xray/config.json")
    if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
        clear
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        judul "      ◈ Config Vmess Account ◈     "
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo
        tebal "          Tidak ada user!!"
        echo
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        kembali
        exec $0 && exit 0
    fi
    clear
    echo
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    judul "      ◈ Config Vmess Account ◈     "
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    tebal "Please choose the client to view the config"
    tebal "ketik [0] kembali ke menu"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    printf "${W}  %-5s %-15s %s\n" "No" "Name" "Expired"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    grep -E "^#vmg " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | nl -s ') ' | while read -r line; do
        number=$(echo "$line" | cut -d')' -f 1 | xargs); name=$(echo "$line" | cut -d' ' -f 2); expired=$(echo "$line" | cut -d' ' -f 3-)
        printf "  %-5s %-15s %s\n" "$number" "$name" "$expired"
    done
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
        if [[ ${NUMBER_OF_CLIENTS} == '1' ]]; then
            read -rp " Select one client [1]: " CLIENT_NUMBER
        else
            read -rp " Select one client [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER
            if [[ ${CLIENT_NUMBER} == '0' ]]; then
                exec $0 && exit 0
            fi
        fi
    done
    clear
    user=$(grep -E "^#vmg " "/etc/xray/config.json" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
    cat /etc/vmess/akun/log-create-${user}.log
    cat /etc/vmess/akun/log-create-${user}.log > /etc/notifakun
    sed -i 's/\x1B\[1;37m//g' /etc/notifakun
    sed -i 's/\x1B\[0;96m//g' /etc/notifakun
    sed -i 's/\x1B\[0m//g' /etc/notifakun
    TEXT=$(cat /etc/notifakun)
    curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
    cd
    if [ ! -e /etc/tele ]; then
        echo -ne
    else
        echo "$TEXT" > /etc/notiftele
        bash /etc/tele
    fi
    kembali
    exec $0 && exit 0
}
clear
function login-vmess(){
    if [[ ! -e /etc/typexray ]]; then
        echo > /etc/typexray
    fi
    if [[ ! -e /etc/waktulock ]]; then
        echo > /etc/waktulock
    fi
    clear
    echo -e " ${U}╭═════════════════════════════════════════╮${N}"
    echo -e " ${U}│${W}       Please select a your Choice       ${U}│${N}"
    echo -e " ${U}╰═════════════════════════════════════════╯${N}"
    echo -e " ${U}╭═════════════════════════════════════════╮${N}"
    echo -e " ${U}│${W} [${U}01${W}] AUTO LOCKED USER ALL XRAY          ${U}│${N}"
    echo -e " ${U}│${W} [${U}02${W}] AUTO DELETE USER ALL XRAY          ${U}│${N}"
    echo -e " ${U}│                                         │${N}"
    echo -e " ${U}│${W} [${U}00${W}] BACK TO MENU                       ${U}│${N}"
    echo -e " ${U}╰═════════════════════════════════════════╯${N}"
    echo
    until [[ $lock =~ ^[0-2]+$ ]]; do
        read -p "  Please select numbers 1 sampai 2 : " lock
    done
    if [[ $lock == "0" ]]; then
        exec menu && exit 0
    elif [[ $lock == "1" ]]; then
        clear
        echo "lock" > /etc/typexray
        echo -e " ${U}╭═══════════════════════════════════════════════╮${N}"
        echo -e " ${U}│${W}            ● SETTING MULTI LOGIN ●            ${U}│${N}"
        echo -e " ${U}╰═══════════════════════════════════════════════╯${N}"
        echo -e " ${U}╭═══════════════════════════════════════════════╮${N}"
        echo -e " ${U}│${W} Succes Ganti Auto Lock                        ${U}│${N}"
        echo -e " ${U}│${W} Jika User Melanggar auto lock Account.        ${U}│${N}"
        echo -e " ${U}╰═══════════════════════════════════════════════╯${N}"
        sleep 1
    elif [[ $lock == "2" ]]; then
        clear
        echo "delete" > /etc/typexray
        echo -e " ${U}╭═══════════════════════════════════════════════╮${N}"
        echo -e " ${U}│${W}            ● SETTING MULTI LOGIN ●            ${U}│${N}"
        echo -e " ${U}╰═══════════════════════════════════════════════╯${N}"
        echo -e " ${U}╭═══════════════════════════════════════════════╮${N}"
        echo -e " ${U}│${W} Succes Ganti Auto Delete Account              ${U}│${N}"
        echo -e " ${U}│${W} Jika User Melanggar auto Delete Account.      ${U}│${N}"
        echo -e " ${U}╰═══════════════════════════════════════════════╯${N}"
        sleep 1
    fi

    type=$(cat /etc/typexray)
    if [ $type = "lock" ]; then
        clear
        echo -e " ${U}╭═══════════════════════════════════════════════╮${N}"
        echo -e " ${U}│${W}            ● SETTING MULTI LOGIN ●            ${U}│${N}"
        echo -e " ${U}╰═══════════════════════════════════════════════╯${N}"
        echo -e " ${U}╭═══════════════════════════════════════════════╮${N}"
        echo -e " ${U}│${W} SILAHKAN TULIS JUMLAH WAKTU UNTUK LOCKED      ${U}│${N}"
        echo -e " ${U}│${W} BISA TULIS 15 MENIT DLL.                      ${U}│${N}"
        echo -e " ${U}╰═══════════════════════════════════════════════╯${N}"
        read -rp "  Jumlah Waktu Lock: " -e notif2
        echo "${notif2}" > /etc/waktulock
        clear
        echo -e " ${U}╭═══════════════════════════════════════════════╮${N}"
        echo -e " ${U}│${W}            ● SETTING MULTI LOGIN ●            ${U}│${N}"
        echo -e " ${U}╰═══════════════════════════════════════════════╯${N}"
        echo -e " ${U}╭═══════════════════════════════════════════════╮${N}"
        echo -e " ${U}│${W} SILAHKAN TULIS JUMLAH NOTIFIKASI AUTO LOCK    ${U}│${N}"
        echo -e " ${U}│${W} AKUN USER YANG MULTI LOGIN                    ${U}│${N}"
        echo -e " ${U}╰═══════════════════════════════════════════════╯${N}"
        read -rp "  Jika Mau 3x Notif baru kelock tulis 3, dst: " -e notif
        echo "$notif" > /etc/vless/notif
        echo "$notif" > /etc/vmess/notif
        echo "$notif" > /etc/trojan/notif
        clear
        echo -e " ${U}╭═══════════════════════════════════════════════╮${N}"
        echo -e " ${U}│${W}            ● SETTING MULTI LOGIN ●            ${U}│${N}"
        echo -e " ${U}╰═══════════════════════════════════════════════╯${N}"
        echo -e " ${U}╭═══════════════════════════════════════════════╮${N}"
        echo -e " ${U}│${W} SUCCES GANTI NOTIF LOCK JADI $notif "
        echo -e " ${U}│${W} SUCCES GANTI TIME NOTIF LOCK JADI $notif2 MENIT"
        echo -e " ${U}╰═══════════════════════════════════════════════╯${N}"
    else
        echo -e " ${U}╭═══════════════════════════════════════════════╮${N}"
        echo -e " ${U}│${W}            ● SETTING MULTI LOGIN ●            ${U}│${N}"
        echo -e " ${U}╰═══════════════════════════════════════════════╯${N}"
        echo -e " ${U}╭═══════════════════════════════════════════════╮${N}"
        echo -e " ${U}│${W} SILAHKAN TULIS JUMLAH WAKTU USER MULTI LOGIN  ${U}│${N}"
        echo -e " ${U}│${W} TIAP MENIT JADI NOTIF TIAP BEBERAPA MENIT.    ${U}│${N}"
        echo -e " ${U}╰═══════════════════════════════════════════════╯${N}"
        read -rp "  Jika Mau 3menit baru keNotif tulis 3, dst: " -e notif2
        echo "# Autokill" >/etc/cron.d/xraylimit
        echo "SHELL=/bin/sh" >>/etc/cron.d/xraylimit
        echo "PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin" >>/etc/cron.d/xraylimit
        echo "*/$notif2 * * * *  root /usr/bin/xraylimit" >>/etc/cron.d/xraylimit
        clear
        echo -e " ${U}╭═══════════════════════════════════════════════╮${N}"
        echo -e " ${U}│${W}            ● SETTING MULTI LOGIN ●            ${U}│${N}"
        echo -e " ${U}╰═══════════════════════════════════════════════╯${N}"
        echo -e " ${U}╭═══════════════════════════════════════════════╮${N}"
        echo -e " ${U}│${W} SILAHKAN TULIS JUMLAH NOTIFIKASI UNTUK LOCK   ${U}│${N}"
        echo -e " ${U}│${W} AKUN USER YANG MULTI LOGIN                    ${U}│${N}"
        echo -e " ${U}╰═══════════════════════════════════════════════╯${N}"
        read -rp "  Jika Mau 3x Notif baru kelock tulis 3, dst: " -e notif
        echo "$notif" > /etc/vless/notif
        echo "$notif" > /etc/vmess/notif
        echo "$notif" > /etc/trojan/notif
        clear
        echo -e " ${U}╭═══════════════════════════════════════════════╮${N}"
        echo -e " ${U}│${W}            ● SETTING MULTI LOGIN ●            ${U}│${N}"
        echo -e " ${U}╰═══════════════════════════════════════════════╯${N}"
        echo -e " ${U}╭═══════════════════════════════════════════════╮${N}"
        echo -e " ${U}│${W} SUCCES GANTI NOTIF LOCK JADI $notif"
        echo -e " ${U}│${W} SUCCES GANTI TIME NOTIF LOCK JADI $notif2 MENIT"
        echo -e " ${U}╰═══════════════════════════════════════════════╯${N}"
    fi
    kembali
    exec $0 && exit 0
}
function lock-vmess(){
    clear
    cd
    if [ ! -e /etc/vmess/listlock ]; then
        echo > /etc/vmess/listlock
    fi
    NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/vmess/listlock")
    if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        judul "      ◈ Unlock Vmess Account ◈     "
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo
        tebal "          Tidak ada user!!"
        echo
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        kembali
        exec $0 && exit 0
    fi
    clear
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    judul "      ◈ Unlock Vmess Account ◈     "
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    tebal "Please choose the client to Unlock"
    tebal "ketik [0] kembali ke menu"
    tebal "ketik [999] untuk delete semua Akun"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    printf "${W}  %-5s %-15s %s\n" "No" "Name" "Expired"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    grep -E "^### " "/etc/vmess/listlock" | cut -d ' ' -f 2-3 | nl -s ') ' | while read -r line; do
        number=$(echo "$line" | cut -d')' -f 1 | xargs); name=$(echo "$line" | cut -d' ' -f 2); expired=$(echo "$line" | cut -d' ' -f 3-)
        printf "  %-5s %-15s %s\n" "$number" "$name" "$expired"
    done
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
        if [[ ${NUMBER_OF_CLIENTS} == '1' ]]; then
            read -rp " Select one client [1]: " CLIENT_NUMBER
        else
            read -rp " Select one client [1-${NUMBER_OF_CLIENTS}] to Unlock: " CLIENT_NUMBER
            if [[ ${CLIENT_NUMBER} == '0' ]]; then
                exec $0 && exit 0
            fi
            if [[ ${CLIENT_NUMBER} == '999' ]]; then
                rm /etc/vmess/listlock
                exec $0 && exit 0
            fi
        fi
    done
    user=$(grep -E "^### " "/etc/vmess/listlock" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
    exp=$(grep -E "^### " "/etc/vmess/listlock" | cut -d ' ' -f 3 | sed -n "${CLIENT_NUMBER}"p)
    uuid=$(grep -E "^### " "/etc/vmess/listlock" | cut -d ' ' -f 4 | sed -n "${CLIENT_NUMBER}"p)
sed -i '/#vmess$/a\#vm '"$user $exp"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' /etc/xray/config.json
sed -i '/#vmessgrpc$/a\#vmg '"$user $exp $uuid"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' /etc/xray/config.json
sed -i "/^### $user $exp $uuid/d" /etc/vmess/listlock
    systemctl restart xray
TEXT="
━━━━━━━━━━━━━━━━━━━━━━━
<b>☘️ XRAY VMESS UNLOCK ☘️</b>
━━━━━━━━━━━━━━━━━━━━━━━
<code>User    :</code> <code>$user</code>
<code>Domain  :</code> <code>${domain}</code>
<code>ISP     :</code> <code>$ISP</code>
<code>CITY    :</code> <code>$CITY</code>
<code>Expired :</code> <code>$exp</code>
━━━━━━━━━━━━━━━━━━━━━━━
<i>Succes Unlock This Account...</i>
"
    curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
    cd
    if [ ! -e /etc/tele ]; then
        echo -ne
    else
        echo "$TEXT" > /etc/notiftele
        bash /etc/tele
    fi
    clear
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    judul " Vmess Account Unlock Successfully "
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    tebal "Client Name : $user"
    tebal "Status      : Unlocked"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo
    bottelegram > /dev/null 2>&1 &
    kembali
    exec $0 && exit 0
}

function res-user(){
    clear
    cd
    if [ ! -e /etc/vmess/akundelete ]; then
        echo > /etc/vmess/akundelete
    fi
    clear
    NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/vmess/akundelete")
    if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        judul "     ◈ Restore Vmess Account ◈     "
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo
        tebal "          Tidak ada user!!"
        echo
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        kembali
        exec $0 && exit 0
    fi
    clear
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    judul "     ◈ Restore Vmess Account ◈     "
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    tebal "Please choose the client to Restore"
    tebal "ketik [0] kembali ke menu"
    tebal "ketik [999] untuk delete semua Akun"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    printf "${W}  %-5s %-15s %s\n" "No" "Name" "Expired"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    grep -E "^### " "/etc/vmess/akundelete" | cut -d ' ' -f 2-3 | nl -s ') ' | while read -r line; do
        number=$(echo "$line" | cut -d')' -f 1 | xargs); name=$(echo "$line" | cut -d' ' -f 2); expired=$(echo "$line" | cut -d' ' -f 3-)
        printf "  %-5s %-15s %s\n" "$number" "$name" "$expired"
    done
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
        if [[ ${NUMBER_OF_CLIENTS} == '1' ]]; then
            read -rp " Select one client [1]: " CLIENT_NUMBER
        else
            read -rp " Select one client [1-${NUMBER_OF_CLIENTS}] to Unlock: " CLIENT_NUMBER
            if [[ ${CLIENT_NUMBER} == '0' ]]; then
                exec $0 && exit 0
            fi
            if [[ ${CLIENT_NUMBER} == '999' ]]; then
                rm /etc/vmess/akundelete
                exec $0 && exit 0
            fi
        fi
    done
    until [[ $masaaktif =~ ^[0-9]+$ ]]; do
        read -p " Expired (days): " masaaktif
    done
    until [[ $iplim =~ ^[0-9]+$ ]]; do
        read -p " Limit User (IP) or 0 Unlimited: " iplim
    done
    until [[ $Quota =~ ^[0-9]+$ ]]; do
        read -p " Limit Quota (GB) or 0 Unlimited: " Quota
    done
    if [ ${iplim} = '0' ]; then
        iplim="999999999"
    fi
    if [ ${Quota} = '0' ]; then
        Quota="999999999"
    fi
    user=$(grep -E "^### " "/etc/vmess/akundelete" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
    exp=$(grep -E "^### " "/etc/vmess/akundelete" | cut -d ' ' -f 3 | sed -n "${CLIENT_NUMBER}"p)
    uuid=$(grep -E "^### " "/etc/vmess/akundelete" | cut -d ' ' -f 4 | sed -n "${CLIENT_NUMBER}"p)
    newdate=$(date -d "$masaaktif days" +"%Y-%m-%d")
sed -i '/#vmess$/a\#vm '"$user $newdate"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' /etc/xray/config.json
sed -i '/#vmessgrpc$/a\#vmg '"$user $newdate $uuid"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' /etc/xray/config.json
    echo "${iplim}" >/etc/vmess/${user}IP
    c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
    d=$((${c} * 1024 * 1024 * 1024))
    if [[ ${c} != "0" ]]; then
        echo "${d}" >/etc/vmess/${user}
    fi
    sed -i "/^### ${user} ${exp} ${uuid}/d" /etc/vmess/akundelete
    systemctl restart xray
TEXT="
━━━━━━━━━━━━━━━━━━━━━━━
<b>☘️ XRAY VMESS RESTORE ☘️</b>
━━━━━━━━━━━━━━━━━━━━━━━
<code>User     :</code> <code>$user</code>
<code>Domain   :</code> <code>${domain}</code>
<code>ISP      :</code> <code>$ISP</code>
<code>CITY     :</code> <code>$CITY</code>
<code>IP Limit :</code> <code>$iplim IP</code>
<code>Quota Limit :</code> <code>$Quota GB</code>
<code>Expired  :</code> <code>$newdate</code>
━━━━━━━━━━━━━━━━━━━━━━━
<i>Succes Restore This Account...</i>
"
    curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
    cd
    if [ ! -e /etc/tele ]; then
        echo -ne
    else
        echo "$TEXT" > /etc/notiftele
        bash /etc/tele
    fi
    clear
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    judul "Vmess Account Restore Successfully "
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    tebal "DOMAIN   : $domain"
    tebal "ISP      : $ISP"
    tebal "USERNAME : $user"
    tebal "IP LIMIT : $iplim IP"
    tebal "EXPIRED  : $newdate"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo
    bottelegram > /dev/null 2>&1 &
    kembali
    exec $0 && exit 0
}

function quota-user(){
    clear
    cd
    if [ ! -e /etc/vmess/userQuota ]; then
        echo > /etc/vmess/userQuota
    fi
    NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/vmess/userQuota")
    if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        judul "      ◈ Unlock Vmess Account ◈     "
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo
        tebal "          Tidak ada user!!"
        echo
        garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        kembali
        exec $0 && exit 0
    fi
    clear
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    judul "      ◈ Unlock Vmess Account ◈     "
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    tebal "Please choose the client to Unlock"
    tebal "ketik [0] kembali ke menu"
    tebal "ketik [999] untuk delete semua Akun"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    printf "${W}  %-5s %-15s %s\n" "No" "Name" "Expired"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    grep -E "^### " "/etc/vmess/userQuota" | cut -d ' ' -f 2-3 | nl -s ') ' | while read -r line; do
        number=$(echo "$line" | cut -d')' -f 1 | xargs); name=$(echo "$line" | cut -d' ' -f 2); expired=$(echo "$line" | cut -d' ' -f 3-)
        printf "  %-5s %-15s %s\n" "$number" "$name" "$expired"
    done
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
        if [[ ${NUMBER_OF_CLIENTS} == '1' ]]; then
            read -rp " Select one client [1]: " CLIENT_NUMBER
        else
            read -rp " Select one client [1-${NUMBER_OF_CLIENTS}] to Unlock: " CLIENT_NUMBER
            if [[ ${CLIENT_NUMBER} == '0' ]]; then
                exec $0 && exit 0
            fi
            if [[ ${CLIENT_NUMBER} == '999' ]]; then
                rm /etc/vmess/userQuota
                exec $0 && exit 0
            fi
        fi
    done
    user=$(grep -E "^### " "/etc/vmess/userQuota" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
    exp=$(grep -E "^### " "/etc/vmess/userQuota" | cut -d ' ' -f 3 | sed -n "${CLIENT_NUMBER}"p)
    uuid=$(grep -E "^### " "/etc/vmess/userQuota" | cut -d ' ' -f 4 | sed -n "${CLIENT_NUMBER}"p)
sed -i '/#vmess$/a\#vm '"$user $exp"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' /etc/xray/config.json
sed -i '/#vmessgrpc$/a\#vmg '"$user $exp $uuid"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' /etc/xray/config.json
sed -i "/^### $user $exp $uuid/d" /etc/vmess/userQuota
    systemctl restart xray
TEXT="
━━━━━━━━━━━━━━━━━━━━━━━
<b>☘️ XRAY VMESS UNLOCK ☘️</b>
━━━━━━━━━━━━━━━━━━━━━━━
<code>User    :</code> <code>$user</code>
<code>Domain  :</code> <code>${domain}</code>
<code>ISP     :</code> <code>$ISP</code>
<code>CITY    :</code> <code>$CITY</code>
<code>Expired :</code> <code>$exp</code>
━━━━━━━━━━━━━━━━━━━━━━━
<i>Succes Unlock This Account...</i>
"
    curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
    cd
    if [ ! -e /etc/tele ]; then
        echo -ne
    else
        echo "$TEXT" > /etc/notiftele
        bash /etc/tele
    fi
    clear
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    judul " Vmess Account Unlock Successfully "
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    tebal "Client Name : $user"
    tebal "Status      : Unlocked"
    garis "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo
    bottelegram > /dev/null 2>&1 &
    kembali
    exec $0 && exit 0
}
clear
echo -e " ${U}╭════════════════════════════════════════════════════╮${N}"
echo -e " ${U}│${N}${O}                ${W}● VMESS PANEL MENU ●                ${N}${U}│${N}"
echo -e " ${U}╰════════════════════════════════════════════════════╯${N}"
echo -e " ${U}╭════════════════════════════════════════════════════╮${N}"
echo -e " ${U}│ ${N}${W}[${U}01${W}]${N} ${U}● ${W}ADD AKUN${N}          ${W}[${U}06${W}]${N} ${U}● ${W}CEK USER CONFIG${N}    ${U}│${N}"
echo -e " ${U}│ ${N}${W}[${U}02${W}]${N} ${U}● ${W}TRIAL AKUN${N}        ${W}[${U}07${W}]${N} ${U}● ${W}CHANGE USER LIMIT${N}  ${U}│${N}"
echo -e " ${U}│ ${N}${W}[${U}03${W}]${N} ${U}● ${W}RENEW AKUN${N}        ${W}[${U}08${W}]${N} ${U}● ${W}SETTING LOCK LOGIN${N} ${U}│${N}"
echo -e " ${U}│ ${N}${W}[${U}04${W}]${N} ${U}● ${W}DELETE AKUN${N}       ${W}[${U}09${W}]${N} ${U}● ${W}UNLOCK USER LOGIN${N}  ${U}│${N}"
echo -e " ${U}│ ${N}${W}[${U}05${W}]${N} ${U}● ${W}CEK USER LOGIN${N}    ${W}[${U}10${W}]${N} ${U}● ${W}UNLOCK USER QUOTA ${N} ${U}│${N}"
echo -e " ${U}│ ${N}${W}[${U}00${W}]${N} ${U}● ${W}GO BACK${N}           ${W}[${U}11${W}]${N} ${U}● ${W}RESTORE AKUN   ${N}    ${U}│${N}"
echo -e " ${U}╰════════════════════════════════════════════════════╯${N}"
echo -e " ${U}╭══════════════════════ ● ${W}BY${N} ${U}● ══════════════════════╮${N}"
cetak_judul
echo -e " ${U}╰════════════════════════════════════════════════════╯${N}"
echo -ne "  ${W}Select menu ${U}: ${W}"; read opt
case $opt in
    01 | 1) clear ; add-vmess ; exit 0 ;;
    02 | 2) clear ; trial-vmess ; exit 0 ;;
    03 | 3) clear ; renew-vmess ; exit 0 ;;
    04 | 4) clear ; del-vmess ; exit 0 ;;
    05 | 5) clear ; cek-vmess ; exit 0 ;;
    06 | 6) clear ; list-vmess ; exit 0 ;;
    07 | 7) clear ; limit-vmess ; exit 0 ;;
    08 | 8) clear ; login-vmess ; exit 0 ;;
    09 | 9) clear ; lock-vmess ; exit 0 ;;
    10 | 10) clear ; quota-user ; exit 0 ;;
    11 | 11) clear ; res-user ; exit 0 ;;
    00 | 0) clear ; exec menu ;  exit 0 ;;
    *) echo -e "  ${R}Input is not valid!${N}" ; sleep 1 ; exec $0 ; exit 0 ;;
esac
exit 0
