#!/bin/bash
exit_clean() { echo " Dihentikan"; exit 0; }
trap exit_clean SIGINT
clear
REPOKU="https://raw.githubusercontent.com/optimus-glitch/newsc/main"
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
ipsaya=$(wget -qO- ipv4.icanhazip.com)
data_ip="${REPOKU}/registrasi.txt"
date_list=$(date +"%Y-%m-%d" -d "$data_server")
useexp=$(curl -sS $data_ip | grep $ipsaya | awk '{print $3}')
checking_sc() {
    useexp=$(curl -sS "$data_ip" | grep "$ipsaya" | awk '{print $3}')
    [[ "$date_list" > "$useexp" ]] && { systemctl stop nginx kyt xray ws-stunnel; dilarang; exit 1; }
}
checking_sc

# Periksa status nginx
nginx_status=$(systemctl is-active nginx)
if [[ $nginx_status == "active" ]]; then
    echo "NGINX dalam keadaan aman"
else
    systemctl restart nginx
    systemctl start nginx
fi

# Periksa status kyt
kyt_status=$(systemctl is-active kyt)
if [[ $kyt_status == "active" ]]; then
    echo "KYT dalam keadaan aman"
else
    systemctl restart kyt
    systemctl start kyt
fi

# Periksa status XRAY
xray_status=$(systemctl is-active xray)
if [[ $xray_status == "active" ]]; then
    echo "XRAY dalam keadaan aman"
else
    systemctl restart xray
    systemctl start xray
fi

# Periksa status sshws
ws_status=$(systemctl is-active ws-stunnel)
if [[ $ws_status == "active" ]]; then
    echo "SSHWS dalam keadaan aman"
else
    systemctl restart ws-stunnel
    systemctl start ws-stunnel
fi

# Hitung persentase status aktif
total_services=4
active_services=0

[[ $nginx_status == "active" ]] && ((active_services++))
[[ $kyt_status == "active" ]] && ((active_services++))
[[ $xray_status == "active" ]] && ((active_services++))
[[ $ws_status == "active" ]] && ((active_services++))

percentage=$((active_services * 100 / total_services))

echo
echo "Status $percentage%"
echo
exit 0
