#!/bin/bash
exit_clean() { echo " Dihentikan"; exit 0; }
trap exit_clean SIGINT
clear
colornow=$(cat /etc/alawivpn/theme/color.conf)
export N='\e[0m'
export W='\e[1;37m'
export COLOR1="$(cat /etc/alawivpn/theme/$colornow | grep -w "TEXT" | cut -d: -f2|sed 's/ //g')"
export COLBG1="$(cat /etc/alawivpn/theme/$colornow | grep -w "BG" | cut -d: -f2|sed 's/ //g')"
U=$COLOR1
O=$COLBG1
function animasiku(){
    fun_bar() {
        CMD[0]="$1"
        CMD[1]="$2"
        (
            [[ -e $HOME/fim ]] && rm $HOME/fim
            ${CMD[0]} -y >/dev/null 2>&1
            ${CMD[1]} -y >/dev/null 2>&1
            touch $HOME/fim
        ) >/dev/null 2>&1 &
        tput civis
        echo -ne " \033[1;33m Sedang restart service \033[1;37m- \033[1;33m["
        while true; do
            for ((i = 0; i < 16; i++)); do
                echo -ne "\033[0;32m●"
                sleep 0.1s
            done
            [[ -e $HOME/fim ]] && rm $HOME/fim && break
            echo -e "\033[0;33m]"
            sleep 1s
            tput cuu1
            tput dl1
            echo -ne " \033[1;33m Sedang restart service \033[1;37m- \033[1;33m["
        done
        echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
        tput cnorm
    }
    res1() { systemctl restart nginx; }
    res2() { systemctl restart xray; }
    res3() { systemctl restart daemon; }
    res4() { systemctl restart udp-custom; }
    res7() { systemctl restart ws-dropbear; }
    res8() { systemctl restart ws-stunnel; }
    res9() { systemctl restart openvpn; }
    res10() { systemctl restart cron; }
    res11() { systemctl restart netfilter-persistent; }
    res12() { systemctl restart squid; }
    res13() { systemctl restart badvpn1; }
    res14() { systemctl restart badvpn2; }
    res15() { systemctl restart badvpn3; }
    res16() { systemctl restart kyt; }
    pro() { echo -e "\\033[37;1m${*}\\033[0m"; }
    echo
    echo -e " ${U}╭══════════════════════════════════════════╮${N}"
    echo -e " ${U}│${W}           RESTART ALL SERVICE            ${U}│${N}"
    echo -e " ${U}╰══════════════════════════════════════════╯${N}"
    pro "  Restart Service NGINX"
    fun_bar 'res1'
    pro "  Restart Service XRAY"
    fun_bar 'res2'
    pro "  Restart Service Daemon"
    fun_bar 'res3'
    pro "  Restart Service UDP-CUSTOM"
    fun_bar 'res4'
    pro "  Restart Service WS-DROPBEAR"
    fun_bar 'res7'
    pro "  Restart Service WS-STUNNEL"
    fun_bar 'res8'
    pro "  Restart Service OPENVPN"
    fun_bar 'res9'
    pro "  Restart Service CRONS"
    fun_bar 'res10'
    pro "  Restart Service NETFILTER-PRESISTENT"
    fun_bar 'res11'
    pro "  Restart Service BADVPN1"
    fun_bar 'res13'
    pro "  Restart Service BADVPN2"
    fun_bar 'res14'
    pro "  Restart Service BADVPN3"
    fun_bar 'res15'
    pro "  Restart Service KYT"
    fun_bar 'res16'
    sleep 2
    exec menu
}
animasiku
exit 0
