#!/bin/bash
exit_clean() { echo " Dihentikan"; exit 0; }
trap exit_clean SIGINT
domain=$(cat /etc/xray/domain)
TIMES="10"
CHATID=$(cat /etc/botexp/id)
KEY=$(cat /etc/botexp/token)
URL="https://api.telegram.org/bot$KEY/sendMessage"
cd
if [ ! -e /etc/vmess/akundelete ]; then touch /etc/vmess/akundelete; fi
if [ ! -e /etc/vless/akundelete ]; then touch /etc/vless/akundelete; fi
if [ ! -e /etc/trojan/akundelete ]; then touch /etc/trojan/akundelete; fi
if [ ! -e /etc/xray/sshx/akundelete ]; then touch /etc/xray/sshx/akundelete; fi

batas=-60
# SSH
folder="/etc/xray/sshx/akundelete"
data=( `cat ${folder} | grep '^###' | cut -d ' ' -f 2 | sort | uniq`);
now=`date +"%Y-%m-%d"`
for user in "${data[@]}"; do
    exp=$(grep -w "^### $user" "${folder}" | cut -d ' ' -f 3 | sort | uniq)
    pass=$(grep -w "^### $user" "${folder}" | cut -d ' ' -f 4 | sort | uniq)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    exp2=$(( (d1 - d2) / 86400 ))
    kadal=$(( exp2 < 0 ? -exp2 : exp2 ))
    if [[ "$exp2" -lt "$batas" ]]; then
        sed -i "/^### $user $exp $pass/d" ${folder}
        TEXT="
━━━━━━━━━━━━━━━━━━━━━━━
<b>   ☘️ FORFEITED SSH ACCOUNT ☘️</b>
━━━━━━━━━━━━━━━━━━━━━━━
<b>» User :</b> <code>$user</code>
<b>» Pass :</b> <code>$pass</code>
<b>» Domain :</b> <code>$domain</code>
<b>» Expires :</b> <code>$kadal Hari</code>
<b>» Status : HANGUS</b>
━━━━━━━━━━━━━━━━━━━━━━━
<b>» @alawivpn</b>
━━━━━━━━━━━━━━━━━━━━━━━
"
        curl -s --max-time "$TIMES" -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" "$URL" >/dev/null
    fi
done

# DEL EXP VMESS
fldrvm="/etc/vmess/akundelete"
data=( `cat ${fldrvm} | grep '^###' | cut -d ' ' -f 2 | sort | uniq`);
now=`date +"%Y-%m-%d"`
for user in "${data[@]}"; do
    exp=$(grep -w "^### $user" "${fldrvm}" | cut -d ' ' -f 3 | sort | uniq)
    uuid=$(grep -w "^### $user" "${fldrvm}" | cut -d ' ' -f 4 | sort | uniq)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    exp2=$(( (d1 - d2) / 86400 ))
    kadal=$(( exp2 < 0 ? -exp2 : exp2 ))
    if [[ "$exp2" -lt "$batas" ]]; then
        sed -i "/^### $user $exp $uuid/d" ${fldrvm}
        TEXT="
━━━━━━━━━━━━━━━━━━━━━━━
<b>☘️ FORFEITED VMESS ACCOUNT ☘️</b>
━━━━━━━━━━━━━━━━━━━━━━━
<b>» User :</b> <code>$user</code>
<b>» Domain :</b> <code>$domain</code>
<b>» Expires :</b> <code>$kadal Hari</code>
<b>» Status : HANGUS</b>
━━━━━━━━━━━━━━━━━━━━━━━
<b>» @alawivpn</b>
━━━━━━━━━━━━━━━━━━━━━━━
"
        curl -s --max-time "$TIMES" -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" "$URL" >/dev/null
    fi
done

#DEL EXP VLESS
fldrvl="/etc/vless/akundelete"
data=( `cat ${fldrvl} | grep '^###' | cut -d ' ' -f 2 | sort | uniq`);
now=`date +"%Y-%m-%d"`
for user in "${data[@]}"; do
    exp=$(grep -w "^### $user" "${fldrvl}" | cut -d ' ' -f 3 | sort | uniq)
    uuid=$(grep -w "^### $user" "${fldrvl}" | cut -d ' ' -f 4 | sort | uniq)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    exp2=$(( (d1 - d2) / 86400 ))
    kadal=$(( exp2 < 0 ? -exp2 : exp2 ))
    if [[ "$exp2" -lt "$batas" ]]; then
        sed -i "/^### $user $exp $uuid/d" ${fldrvl}
        TEXT="
━━━━━━━━━━━━━━━━━━━━━━━
<b>☘️ FORFEITED VLESS ACCOUNT ☘️</b>
━━━━━━━━━━━━━━━━━━━━━━━
<b>» User :</b> <code>$user</code>
<b>» Domain :</b> <code>$domain</code>
<b>» Expires :</b> <code>$kadal Hari</code>
<b>» Status : HANGUS</b>
━━━━━━━━━━━━━━━━━━━━━━━
<b>» @alawivpn</b>
━━━━━━━━━━━━━━━━━━━━━━━
"
        curl -s --max-time "$TIMES" -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" "$URL" >/dev/null
    fi
done

# DEL EXP TROJAN
fldrtr="/etc/trojan/akundelete"
data=( `cat ${fldrtr} | grep '^###' | cut -d ' ' -f 2 | sort | uniq`);
now=`date +"%Y-%m-%d"`
for user in "${data[@]}"; do
    exp=$(grep -w "^### $user" "${fldrtr}" | cut -d ' ' -f 3 | sort | uniq)
    uuid=$(grep -w "^### $user" "${fldrtr}" | cut -d ' ' -f 4 | sort | uniq)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    exp2=$(( (d1 - d2) / 86400 ))
    kadal=$(( exp2 < 0 ? -exp2 : exp2 ))
    if [[ "$exp2" -lt "$batas" ]]; then
        sed -i "/^### $user $exp $uuid/d" ${fldrtr}
        TEXT="
━━━━━━━━━━━━━━━━━━━━━━━
<b>☘️ FORFEITED TROJAN ACCOUNT ☘️</b>
━━━━━━━━━━━━━━━━━━━━━━━
<b>» User :</b> <code>$user</code>
<b>» Domain :</b> <code>$domain</code>
<b>» Expires :</b> <code>$kadal Hari</code>
<b>» Status : HANGUS</b>
━━━━━━━━━━━━━━━━━━━━━━━
<b>» @alawivpn</b>
━━━━━━━━━━━━━━━━━━━━━━━
"
        curl -s --max-time "$TIMES" -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" "$URL" >/dev/null
    fi
done
exit 0
