#!/bin/bash
clear
TIMES="10"
CHATID=$(cat /etc/botexp/id)
KEY=$(cat /etc/botexp/token)
URL="https://api.telegram.org/bot$KEY/sendMessage"
domain=$(cat /etc/xray/domain)

# Path ke file yang berisi daftar akun SSH yang terkunci
sshloc="/etc/xray/sshx/listlock"
vmloc="/etc/vmess/listlock"
vlloc="/etc/vless/listlock"
trloc="/etc/trojan/listlock"

convert() {
    local T=$1
    local H=${T:0:2}
    local M=${T:3:2}
    local S=${T:6:2}
    # Hilangkan awalan nol yang tidak perlu
    H=$(echo $H | sed 's/^0*//')
    M=$(echo $M | sed 's/^0*//')
    S=$(echo $S | sed 's/^0*//')
    echo $((H * 3600 + M * 60 + S))
}

# Fungsi untuk memeriksa dan meng-unlock akun SSH yang terkunci
sshws() {
    while IFS= read -r line; do
        if [[ $line == \#\#\#* ]]; then
            user=$(echo $line | awk '{print $2}')
            exp=$(echo $line | awk '{print $3}')
            pass=$(echo $line | awk '{print $4}')
            lock=$(echo $line | awk '{print $5}')
            now=$(date +'%H:%M:%S')
            A=$(convert "$lock")
            B=$(convert "$now")
            # Pastikan variabel A dan B memiliki nilai
            if [ -z "$A" ] || [ -z "$B" ]; then
                echo "Error: Variabel A atau B kosong"
                continue
            fi
            if [ $B -lt $A ]; then
                D=$((B + 86400 - A))
            else
                D=$((B - A))
            fi
            if [ $D -ge 1800 ]; then
                passwd -u "$user"
                echo -e "### $user $exp $pass" >> /etc/xray/ssh
				urut "/etc/xray/ssh"
                sed -i "/$line/d" "$sshloc"
                TEXT="
━━━━━━━━━━━━━━━━━━━━━━━
<b>☘ UNLOCK OTOMATIS 30 MENIT ☘</b>
━━━━━━━━━━━━━━━━━━━━━━━
<b>» User     :</b> <code>$user</code>
<b>» Domain   :</b> <code>$domain</code>
<b>» Locked   :</b> <code>$lock</code>
<b>» Unlocked :</b> <code>$now</code>
━━━━━━━━━━━━━━━━━━━━━━━
<b><i>» Script By: Alawi VPN</i></b>"
                curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
            fi
        fi
    done < "$sshloc"
}

# vmess vless trojan
allinone() {
    jenis="$1"
    loc="$2"
    while IFS= read -r line; do
        if [[ $line == \#\#\#* ]]; then
            user=$(echo "$line" | awk '{print $2}')
            exp=$(echo "$line" | awk '{print $3}')
            uuid=$(echo "$line" | awk '{print $4}')
            lock=$(echo "$line" | awk '{print $5}')
            now=$(date +'%H:%M:%S')
            A=$(convert "$lock")
            B=$(convert "$now")

            # Pastikan variabel A dan B memiliki nilai
            if [ -z "$A" ] || [ -z "$B" ]; then
                echo "Error: Variabel A atau B kosong"
                continue
            fi

            # Hitung selisih waktu dalam detik
            if [ $B -lt $A ]; then
                D=$((B + 86400 - A))
            else
                D=$((B - A))
            fi

            # Cek apakah waktu sudah lebih dari 1800 detik (30 menit)
            if [ $D -ge 1800 ]; then
                case "$jenis" in
                    vm)
                        nama="Vmess"
                        kode="vm"
                        ;;
                    vl)
                        nama="Vless"
                        kode="vl"
                        ;;
                    tr)
                        nama="Trojan"
                        kode="tr"
                        ;;
                    *)
                        echo "Jenis layanan tidak valid: $jenis"
                        continue
                        ;;
                esac

                # Tambahkan konfigurasi ke file /etc/xray/config.json
                if [[ $jenis == "vm" ]]; then
                    sed -i '/#vmess$/a\#vm '"$user $exp"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' /etc/xray/config.json
                    sed -i '/#vmessgrpc$/a\#vmg '"$user $exp $uuid"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' /etc/xray/config.json
                elif [[ $jenis == "vl" ]]; then
                    sed -i '/#vless$/a\#vl '"$user $exp $uuid"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
                    sed -i '/#vlessgrpc$/a\#vlg '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
                elif [[ $jenis == "tr" ]]; then
                    sed -i '/#trojanws$/a\#tr '"$user $exp $uuid"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
                    sed -i '/#trojangrpc$/a\#trg '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
                fi

                # Hapus baris yang sesuai dari file yang sesuai (${jenis}loc)
                sed -i "/$line/d" "$loc"
                systemctl restart xray
                # Kirim notifikasi ke Telegram
                TEXT="
━━━━━━━━━━━━━━━━━━━━━━━
<b>☘ UNLOCK OTOMATIS 30 MENIT ☘</b>
━━━━━━━━━━━━━━━━━━━━━━━
<b>» User     :</b> <code>$user</code>
<b>» Jenis    :</b> <code>$nama</code>
<b>» Domain   :</b> <code>$domain</code>
<b>» Locked   :</b> <code>$lock</code>
<b>» Unlocked :</b> <code>$now</code>
━━━━━━━━━━━━━━━━━━━━━━━
<b><i>» Script By: Alawi VPN</i></b>"

                curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" "$URL" >/dev/null
            fi
        fi
    done < "$loc"
}

# Memanggil fungsi dengan if-elif-else biar tidak menumpuk hehe
if [[ -e "$sshloc" ]] && grep -q '^###' "$sshloc"; then
    sshws
elif [[ -e "$vmloc" ]] && grep -q '^###' "$vmloc"; then
    allinone "vm" "$vmloc"
elif [[ -e "$vlloc" ]] && grep -q '^###' "$vlloc"; then
    allinone "vl" "$vlloc"
elif [[ -e "$trloc" ]] && grep -q '^###' "$trloc"; then
    allinone "tr" "$trloc"
else
    echo "Tidak ada baris yang diawali dengan ### di file yang diperiksa"
    exit 1
fi
exit 0

