#!/bin/bash
clear

if [ "$#" -ne 1 ]; then
  echo "Penggunaan yang benar: ./$0 nama_file"
  exit 1
fi

file="$1"
sorted_file="${file}_sorted"

sort -o "$sorted_file" -k1,1 "$file"

mv "$sorted_file" "$file"

exit 0
